#!/usr/bin/env python3
"""
Header management utilities for QSP metadata files.

Provides centralized management of header fields (metadata about files)
vs content fields (scientific data extracted/generated by LLMs).

Key principles:
- Headers are stripped from templates before sending to LLMs
- Headers are preserved when fixing validation errors
- Headers are added back during unpacking with appropriate values
"""

import yaml
from pathlib import Path
from typing import Dict, List, Tuple, Optional

from qsp_llm_workflows.core.resource_utils import get_config_path


class HeaderManager:
    """Manages header field definitions and operations for QSP metadata."""

    def __init__(self, base_dir: Path):
        """
        Initialize header manager.

        Args:
            base_dir: Base directory of qsp-llm-workflows (where templates/ is located)
        """
        self.base_dir = Path(base_dir)
        self.config = self._load_config()

    def _load_config(self) -> Dict:
        """Load header field configuration from YAML file."""
        config_path = get_config_path("header_fields.yaml")

        if not config_path.exists():
            raise FileNotFoundError(
                f"Header fields config not found: {config_path}\n"
                "Expected: templates/configs/header_fields.yaml"
            )

        with open(config_path, 'r', encoding='utf-8') as f:
            return yaml.safe_load(f)

    def get_header_fields(self, template_type: str, schema_version: str) -> List[str]:
        """
        Get list of header field names for a template type and version.

        Args:
            template_type: Type of template (parameter_metadata, test_statistic)
            schema_version: Schema version (e.g., "v3", "v2", "v1")

        Returns:
            List of header field names

        Raises:
            KeyError: If template_type or schema_version not found in config
        """
        try:
            return self.config[template_type][schema_version]['header_fields']
        except KeyError:
            raise KeyError(
                f"No header fields defined for {template_type} {schema_version}\n"
                f"Check templates/configs/header_fields.yaml"
            )

    def get_content_start_field(self, template_type: str, schema_version: str) -> str:
        """
        Get the field name where content section begins.

        Args:
            template_type: Type of template
            schema_version: Schema version

        Returns:
            Field name where content starts (e.g., "mathematical_role")

        Raises:
            KeyError: If template_type or schema_version not found in config
        """
        try:
            return self.config[template_type][schema_version]['content_starts_at']
        except KeyError:
            raise KeyError(
                f"No content_starts_at defined for {template_type} {schema_version}\n"
                f"Check templates/configs/header_fields.yaml"
            )

    def strip_headers_from_yaml_string(
        self,
        yaml_content: str,
        template_type: str,
        schema_version: str
    ) -> Tuple[Dict, Dict]:
        """
        Split YAML content into headers and content dictionaries.

        Args:
            yaml_content: Full YAML content as string
            template_type: Type of template
            schema_version: Schema version

        Returns:
            Tuple of (headers_dict, content_dict)

        Example:
            headers, content = manager.strip_headers_from_yaml_string(yaml_str, "parameter_metadata", "v3")
            # headers = {"parameter_name": "k_CD8_pro", "cancer_type": "PDAC", ...}
            # content = {"mathematical_role": "...", "parameter_estimates": {...}, ...}
        """
        # Parse YAML
        data = yaml.safe_load(yaml_content)

        # Get header field names for this template type
        header_field_names = self.get_header_fields(template_type, schema_version)

        # Split into headers and content
        headers = {}
        content = {}

        for key, value in data.items():
            if key in header_field_names:
                headers[key] = value
            else:
                content[key] = value

        return headers, content

    def strip_headers_from_template(
        self,
        template_path: Path,
        template_type: Optional[str] = None,
        schema_version: Optional[str] = None
    ) -> str:
        """
        Load template file and return only content section (strip headers).

        This is used when including templates in LLM prompts - we only want to
        show content fields, not header fields.

        Args:
            template_path: Path to template file
            template_type: Type of template (auto-detected if None)
            schema_version: Schema version (auto-detected if None)

        Returns:
            YAML string containing only content fields

        Example:
            content_yaml = manager.strip_headers_from_template(
                base_dir / "templates" / "parameter_metadata_template.yaml"
            )
            # Returns YAML starting from mathematical_role onward
        """
        # Read template file
        with open(template_path, 'r', encoding='utf-8') as f:
            template_content = f.read()

        # Auto-detect template type and version if not provided
        if template_type is None or schema_version is None:
            detected_type, detected_version = self._detect_template_type(template_content)
            template_type = template_type or detected_type
            schema_version = schema_version or detected_version

        # Get the field where content starts
        content_start_field = self.get_content_start_field(template_type, schema_version)

        # Find the line where content section begins
        lines = template_content.split('\n')
        content_start_idx = None

        for i, line in enumerate(lines):
            # Look for the content start field (e.g., "mathematical_role:")
            if line.strip().startswith(f"{content_start_field}:"):
                content_start_idx = i
                break

        if content_start_idx is None:
            # Fallback: return original if we can't find content start
            print(f"Warning: Could not find '{content_start_field}' field in template")
            return template_content

        # Return content section only
        content_lines = lines[content_start_idx:]
        return '\n'.join(content_lines)

    def _detect_template_type(self, template_content: str) -> Tuple[str, str]:
        """
        Auto-detect template type and schema version from content.

        Args:
            template_content: YAML template content

        Returns:
            Tuple of (template_type, schema_version)
        """
        data = yaml.safe_load(template_content)

        # Detect schema version
        schema_version = data.get('schema_version', 'v1')

        # Detect template type based on fields
        if 'parameter_name' in data:
            return 'parameter_metadata', schema_version
        elif 'test_statistic_id' in data:
            return 'test_statistic', schema_version
        else:
            # Default to parameter_metadata
            return 'parameter_metadata', schema_version

    def extract_headers_from_file(
        self,
        yaml_path: Path,
        template_type: str,
        schema_version: Optional[str] = None
    ) -> Optional[Dict]:
        """
        Extract header fields from an existing YAML file.

        Args:
            yaml_path: Path to YAML file
            template_type: Type of template
            schema_version: Schema version (auto-detected if None)

        Returns:
            Dictionary with header fields, or None if file cannot be read
        """
        try:
            with open(yaml_path, 'r', encoding='utf-8') as f:
                data = yaml.safe_load(f)

            # Auto-detect schema version if not provided
            if schema_version is None:
                schema_version = data.get('schema_version', 'v1')

            # Get header field names for this template type
            header_field_names = self.get_header_fields(template_type, schema_version)

            # Extract header fields
            headers = {}
            for field in header_field_names:
                if field in data:
                    headers[field] = data[field]

            return headers if headers else None

        except Exception as e:
            print(f"Warning: Could not extract headers from {yaml_path}: {e}")
            return None

    def merge_headers_and_content(
        self,
        headers_dict: Dict,
        content_dict: Dict,
        schema_header_fields: Optional[List[str]] = None
    ) -> str:
        """
        Combine header and content dictionaries into full YAML string.

        Args:
            headers_dict: Dictionary of header fields
            content_dict: Dictionary of content fields
            schema_header_fields: Optional ordered list of header fields (for ordering)

        Returns:
            Complete YAML string with headers first, then content
        """
        # Merge dictionaries (headers first)
        full_data = {}

        # Add headers in specified order if provided
        if schema_header_fields:
            for field in schema_header_fields:
                if field in headers_dict:
                    full_data[field] = headers_dict[field]
            # Add any remaining headers not in schema list
            for key, value in headers_dict.items():
                if key not in full_data:
                    full_data[key] = value
        else:
            # No order specified, add all headers
            full_data.update(headers_dict)

        # Add content fields
        full_data.update(content_dict)

        # Convert to YAML with proper formatting
        yaml_str = yaml.dump(
            full_data,
            default_flow_style=False,
            allow_unicode=True,
            sort_keys=False,
            width=120
        )

        return yaml_str
