#!/usr/bin/env python3
"""
Header management utilities for QSP metadata files.

Provides centralized management of header fields (metadata about files)
vs content fields (scientific data extracted/generated by LLMs).

Key principles:
- Headers are stripped from templates before sending to LLMs
- Headers are preserved when fixing validation errors
- Headers are added back during unpacking with appropriate values

This implementation uses Pydantic models for type-safe header management.
"""

import yaml
from pathlib import Path
from typing import TypeVar, Union
from pydantic import BaseModel

from qsp_llm_workflows.core.pydantic_models import (
    ParameterMetadata,
    ParameterFooters,
    TestStatistic,
    TestStatisticFooters,
    ModelRegistry,
)

# Type variables for generic methods
T = TypeVar("T", bound=BaseModel)
HeaderModel = Union[ParameterFooters, TestStatisticFooters]
ContentModel = Union[ParameterMetadata, TestStatistic]


class HeaderManager:
    """
    Manages header field operations using Pydantic models.

    This replaces the old YAML config-based approach with a type-safe
    Pydantic-based system.
    """

    def __init__(self):
        """Initialize header manager (no config file needed)."""
        pass

    def split_model(self, model: BaseModel) -> tuple[BaseModel, dict]:
        """
        Split a complete model into headers and content.

        Args:
            model: Complete model instance (ParameterMetadata or TestStatistic)

        Returns:
            Tuple of (header_model, content_dict)

        Example:
            headers, content = manager.split_model(param_metadata)
            # headers: ParameterFooters instance
            # content: dict with LLM-generated fields
        """
        if not hasattr(model, "split"):
            raise ValueError(
                f"Model {type(model).__name__} doesn't have split() method. "
                "Make sure it's a ParameterMetadata or TestStatistic instance."
            )

        return model.split()

    def merge_headers_and_content(
        self, headers: BaseModel, content: dict, model_class: type[T]
    ) -> T:
        """
        Merge headers and content into a complete model.

        Args:
            headers: Header model instance (ParameterFooters or TestStatisticFooters)
            content: Content dictionary with LLM-generated fields
            model_class: Target model class (ParameterMetadata or TestStatistic)

        Returns:
            Complete model instance

        Example:
            full_model = manager.merge_headers_and_content(
                headers=ParameterFooters(...),
                content={...},
                model_class=ParameterMetadata
            )
        """
        if not hasattr(model_class, "from_split"):
            raise ValueError(f"Model {model_class.__name__} doesn't have from_split() class method")

        return model_class.from_split(headers, content)

    def extract_headers_from_yaml(self, yaml_path: Path, model_class: type[BaseModel]) -> BaseModel:
        """
        Extract headers from an existing YAML file.

        Args:
            yaml_path: Path to YAML file
            model_class: Complete model class (ParameterMetadata or TestStatistic)

        Returns:
            Header model instance

        Example:
            headers = manager.extract_headers_from_yaml(
                Path("file.yaml"),
                ParameterMetadata
            )
            # Returns ParameterFooters instance
        """
        # Load YAML
        with open(yaml_path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)

        # Get header model class
        header_class = ModelRegistry.get_header_model(model_class)

        # Extract only header fields
        header_data = {k: v for k, v in data.items() if k in header_class.model_fields}

        return header_class(**header_data)

    def strip_headers_from_yaml(
        self, yaml_path: Path, model_class: type[BaseModel]
    ) -> tuple[BaseModel, dict]:
        """
        Load YAML and split into headers and content.

        Args:
            yaml_path: Path to YAML file
            model_class: Complete model class

        Returns:
            Tuple of (header_model, content_dict)
        """
        # Load YAML
        with open(yaml_path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)

        # Get header model class
        header_class = ModelRegistry.get_header_model(model_class)
        header_field_names = set(header_class.model_fields.keys())

        # Split into headers and content
        header_data = {k: v for k, v in data.items() if k in header_field_names}
        content_data = {k: v for k, v in data.items() if k not in header_field_names}

        headers = header_class(**header_data)
        return headers, content_data

    def get_header_field_names(self, model_class: type[BaseModel]) -> set[str]:
        """
        Get set of header field names for a model class.

        Args:
            model_class: Complete model class

        Returns:
            Set of header field names
        """
        header_class = ModelRegistry.get_header_model(model_class)
        return set(header_class.model_fields.keys())

    def is_header_field(self, field_name: str, model_class: type[BaseModel]) -> bool:
        """
        Check if a field name is a header field.

        Args:
            field_name: Field name to check
            model_class: Complete model class

        Returns:
            True if field is a header field
        """
        header_fields = self.get_header_field_names(model_class)
        return field_name in header_fields

    def merge_to_yaml(self, headers: BaseModel, content: dict, output_path: Path) -> None:
        """
        Merge headers and content and write to YAML file.

        Args:
            headers: Header model instance
            content: Content dictionary
            output_path: Path to write YAML file
        """
        # Merge into single dict (headers first for ordering)
        full_data = {**headers.model_dump(), **content}

        # Write to YAML
        with open(output_path, "w", encoding="utf-8") as f:
            yaml.dump(
                full_data,
                f,
                default_flow_style=False,
                allow_unicode=True,
                sort_keys=False,
                width=120,
            )
