#!/usr/bin/env python3
"""
Pydantic models for OpenAI Structured Outputs.

These models define the structure of LLM-generated content for parameter
extraction and test statistic generation, excluding header fields that are
added during post-processing.
"""

from typing import List, Optional
from pydantic import BaseModel, Field


# ============================================================================
# Shared Models
# ============================================================================


class Input(BaseModel):
    """An input value used in parameter or test statistic derivation."""

    name: str = Field(description="Input name")
    value: float = Field(description="Input value")
    units: str = Field(description="Input units")
    description: str = Field(description="Input description")
    source_ref: Optional[str] = Field(description="Source reference tag (or null)")
    value_table_or_section: Optional[str] = Field(description="Location of value in source")
    value_snippet: Optional[str] = Field(description="Text snippet containing value")
    units_table_or_section: Optional[str] = Field(description="Location of units in source")
    units_snippet: Optional[str] = Field(description="Text snippet containing units")


class Source(BaseModel):
    """A bibliographic source (primary or secondary data)."""

    source_tag: str = Field(description="Unique tag for referencing")
    title: str = Field(description="Full title")
    first_author: str = Field(description="First author last name")
    year: int = Field(description="Publication year")
    doi: Optional[str] = Field(None, description="DOI (or null)")


class SecondarySource(BaseModel):
    """A secondary data source (reference values, textbooks)."""

    source_tag: str = Field(description="Unique tag for referencing")
    title: str = Field(description="Full title")
    first_author: str = Field(description="First author last name")
    year: int = Field(description="Publication year")
    doi_or_url: Optional[str] = Field(None, description="DOI or URL (or null)")


class MethodologicalSource(BaseModel):
    """A methodological source (formulas, conversion factors)."""

    source_tag: str = Field(description="Unique tag for referencing")
    title: str = Field(description="Full title")
    first_author: str = Field(description="First author last name")
    year: int = Field(description="Publication year")
    doi_or_url: Optional[str] = Field(None, description="DOI or URL (or null)")
    used_for: str = Field(description="What this source is used for")
    method_description: str = Field(description="Description of the method")


class WeightScore(BaseModel):
    """A rubric-based weight score with justification."""

    value: float = Field(description="Rubric value (0-1)")
    justification: str = Field(description="Justification for this value")


# ============================================================================
# Parameter Extraction Models
# ============================================================================


class ParameterEstimates(BaseModel):
    """Parameter estimates with structured inputs and derivation."""

    inputs: List[Input] = Field(description="List of inputs used in derivation")
    derivation_code: str = Field(description="Python code for derivation (in code fence)")
    median: float = Field(description="Median value")
    iqr: float = Field(description="Interquartile range")
    ci95: List[float] = Field(description="95% confidence interval [lower, upper]")
    units: str = Field(description="Units of the estimate")


class KeyAssumption(BaseModel):
    """A single key assumption with its number and text."""

    number: int = Field(description="Assumption number (1, 2, 3, ...)")
    text: str = Field(description="Assumption text")


class BiologicalRelevance(BaseModel):
    """Biological relevance weights for parameter estimates."""

    species_match: WeightScore
    system_match: WeightScore
    overall_confidence: WeightScore
    indication_match: WeightScore
    regimen_match: WeightScore
    biomarker_population_match: WeightScore
    stage_burden_match: WeightScore


class ParameterMetadata(BaseModel):
    """
    Complete parameter metadata generated by LLM.

    Excludes header fields that are added during unpacking:
    - schema_version, parameter_name, parameter_units, parameter_definition
    - cancer_type, tags, derivation_id, derivation_timestamp
    - model_context, context_hash
    """

    mathematical_role: str = Field(
        description="Mathematical role of parameter in model equations"
    )
    parameter_range: str = Field(
        description="Valid range for parameter (e.g., 'positive_reals', '[0,1]')"
    )
    study_overview: str = Field(
        description="High-level scientific context (WHAT and WHY) in 1-2 sentences"
    )
    study_design: str = Field(
        description="Concrete experimental details (HOW) in 1-2 sentences"
    )
    parameter_estimates: ParameterEstimates = Field(
        description="Parameter estimates with inputs and derivation"
    )
    key_assumptions: List[KeyAssumption] = Field(
        description="List of key assumptions with numbers and text"
    )
    derivation_explanation: str = Field(
        description="Step-by-step explanation of derivation code with assumption justifications"
    )
    key_study_limitations: str = Field(
        description="Important limitations and their impact on reliability"
    )
    primary_data_sources: List[Source] = Field(
        description="Primary data sources (original measurements)"
    )
    secondary_data_sources: List[SecondarySource] = Field(
        description="Secondary data sources (reference values, constants)"
    )
    methodological_sources: List[MethodologicalSource] = Field(
        description="Methodological sources (formulas, analysis methods)"
    )
    biological_relevance: BiologicalRelevance = Field(
        description="Biological relevance weights"
    )


# ============================================================================
# Test Statistic Models
# ============================================================================


class ModelOutput(BaseModel):
    """Model output computation specification."""

    code: str = Field(
        description="Python code to compute test statistic from model simulation (in code fence)"
    )


class TestStatisticEstimates(BaseModel):
    """Test statistic estimates with structured inputs and derivation."""

    inputs: List[Input] = Field(description="List of inputs used in derivation")
    derivation_code: str = Field(
        description="Python code for bootstrap derivation (in code fence)"
    )
    median: float = Field(description="Median value")
    iqr: float = Field(description="Interquartile range")
    ci95: List[float] = Field(description="95% confidence interval [lower, upper]")
    units: str = Field(description="Units of the test statistic")
    key_assumptions: List[KeyAssumption] = Field(
        description="List of key assumptions with numbers and text"
    )


class ValidationWeights(BaseModel):
    """Validation weights for test statistics."""

    species_match: WeightScore
    system_match: WeightScore
    overall_confidence: WeightScore
    indication_match: WeightScore
    regimen_match: WeightScore
    biomarker_population_match: WeightScore
    stage_burden_match: WeightScore


class TestStatistic(BaseModel):
    """
    Complete test statistic generated by LLM.

    Excludes header fields that are added during unpacking:
    - schema_version, test_statistic_id, cancer_type
    - scenario_context, model_context, tags, context_hash
    - required_species, derived_species_description
    """

    model_output: ModelOutput = Field(
        description="Model output computation specification"
    )
    test_statistic_definition: str = Field(
        description="Mathematical definition of the test statistic"
    )
    study_overview: str = Field(
        description="High-level biological context (WHAT and WHY) in 1-2 sentences"
    )
    study_design: str = Field(
        description="Concrete experimental details (HOW) in 1-2 sentences"
    )
    test_statistic_estimates: TestStatisticEstimates = Field(
        description="Test statistic estimates with inputs and derivation"
    )
    derivation_explanation: str = Field(
        description="Step-by-step explanation of derivation code with assumption justifications"
    )
    key_study_limitations: str = Field(
        description="Important limitations and their impact on reliability"
    )
    primary_data_sources: List[Source] = Field(
        description="Primary data sources (original measurements)"
    )
    secondary_data_sources: List[SecondarySource] = Field(
        description="Secondary data sources (reference values, constants)"
    )
    methodological_sources: List[MethodologicalSource] = Field(
        description="Methodological sources (formulas, analysis methods)"
    )
    validation_weights: ValidationWeights = Field(description="Validation weights")
