#!/usr/bin/env python3
"""
Pydantic models for OpenAI Structured Outputs.

These models define the structure of LLM-generated content for parameter
extraction and test statistic generation, excluding header fields that are
added during post-processing.
"""

from typing import List, Optional
from pydantic import BaseModel, Field

from qsp_llm_workflows.core.calibration_target_models import (
    CalibrationTarget,
    CalibrationTargetHeaders,
)
from qsp_llm_workflows.core.shared_models import Input, KeyAssumption, WeightScore


class Source(BaseModel):
    """A bibliographic source (primary or secondary data)."""

    source_tag: str = Field(description="Unique tag for referencing")
    title: str = Field(description="Full title")
    first_author: str = Field(description="First author last name")
    year: int = Field(description="Publication year")
    doi: Optional[str] = Field(None, description="DOI (or null)")


class SecondarySource(BaseModel):
    """A secondary data source (reference values, textbooks)."""

    source_tag: str = Field(description="Unique tag for referencing")
    title: str = Field(description="Full title")
    first_author: str = Field(description="First author last name")
    year: int = Field(description="Publication year")
    doi_or_url: Optional[str] = Field(None, description="DOI or URL (or null)")


# ============================================================================
# Parameter Extraction Models
# ============================================================================


class ParameterEstimates(BaseModel):
    """Parameter estimates with structured inputs and derivation."""

    inputs: List[Input] = Field(description="List of inputs used in derivation")
    derivation_code: str = Field(
        description=(
            "Python code defining a derive_parameter(inputs, ureg) function. "
            "inputs is a dict mapping input names to Pint Quantities. "
            "Access values like: inputs['half_life'] (already a Pint Quantity). "
            "Must return dict with Pint Quantities: median_param, iqr_param, "
            "ci95_param ([lower, upper])."
        )
    )
    median: float = Field(description="Median value")
    iqr: float = Field(description="Interquartile range")
    ci95: List[float] = Field(description="95% confidence interval [lower, upper]")
    units: str = Field(description="Units of the estimate")


class BiologicalRelevance(BaseModel):
    """Biological relevance weights for parameter estimates."""

    species_match: WeightScore
    system_match: WeightScore
    overall_confidence: WeightScore
    indication_match: WeightScore
    regimen_match: WeightScore
    biomarker_population_match: WeightScore
    stage_burden_match: WeightScore


# ============================================================================
# Header Models (Metadata about files, not generated by LLM)
# ============================================================================


class ParameterHeaders(BaseModel):
    """
    Header fields for parameter metadata files.

    These are metadata about the file itself (not generated by LLM):
    - What parameter is being estimated
    - Which cancer type and model context
    - When and how it was derived
    """

    schema_version: str = Field(description="Schema version (e.g., 'v3')")
    parameter_name: str = Field(description="Parameter name from model")
    parameter_units: str = Field(description="Parameter units")
    parameter_definition: str = Field(description="Parameter definition from model")
    cancer_type: str = Field(description="Cancer type (e.g., 'PDAC')")
    tags: List[str] = Field(default_factory=list, description="Metadata tags")
    derivation_id: Optional[str] = Field(None, description="Unique derivation identifier")
    derivation_timestamp: Optional[str] = Field(None, description="ISO timestamp of derivation")
    model_context: dict = Field(description="Model context (reactions, rules, related parameters)")


class ParameterMetadata(BaseModel):
    """
    Complete parameter metadata (headers + LLM-generated content).

    This flat structure is used for:
    - OpenAI Structured Outputs (JSON Schema)
    - Full YAML files after unpacking

    Headers are stripped before sending to LLM, then added back during unpacking.
    """

    mathematical_role: str = Field(description="Mathematical role of parameter in model equations")
    parameter_range: str = Field(
        description="Valid range for parameter (e.g., 'positive_reals', '[0,1]')"
    )
    study_overview: str = Field(
        description="High-level scientific context (WHAT and WHY) in 1-2 sentences"
    )
    study_design: str = Field(description="Concrete experimental details (HOW) in 1-2 sentences")
    parameter_estimates: ParameterEstimates = Field(
        description="Parameter estimates with inputs and derivation"
    )
    key_assumptions: List[KeyAssumption] = Field(
        description="List of key assumptions with numbers and text"
    )
    derivation_explanation: str = Field(
        description="Step-by-step explanation of derivation code with assumption justifications"
    )
    key_study_limitations: str = Field(
        description="Important limitations and their impact on reliability"
    )
    primary_data_sources: List[Source] = Field(
        description="Primary data sources (original measurements)"
    )
    secondary_data_sources: List[SecondarySource] = Field(
        description="Secondary data sources (reference values, constants)"
    )
    biological_relevance: BiologicalRelevance = Field(description="Biological relevance weights")

    @classmethod
    def get_header_fields(cls) -> set[str]:
        """Get set of field names that are headers (from ParameterHeaders)."""
        return set(ParameterHeaders.model_fields.keys())

    def split(self) -> tuple[ParameterHeaders, dict]:
        """
        Split into headers and content.

        Returns:
            Tuple of (headers_model, content_dict)
        """
        header_fields = self.get_header_fields()
        all_data = self.model_dump()

        # Extract headers
        header_data = {k: v for k, v in all_data.items() if k in header_fields}
        headers = ParameterHeaders(**header_data)

        # Extract content
        content = {k: v for k, v in all_data.items() if k not in header_fields}

        return headers, content

    @classmethod
    def from_split(cls, headers: ParameterHeaders, content: dict) -> "ParameterMetadata":
        """
        Create ParameterMetadata from headers and content.

        Args:
            headers: ParameterHeaders instance
            content: Content dictionary (LLM-generated fields)

        Returns:
            Complete ParameterMetadata instance
        """
        return cls(**{**headers.model_dump(), **content})


# ============================================================================
# Test Statistic Models
# ============================================================================


class ModelOutput(BaseModel):
    """Model output computation specification."""

    code: str = Field(
        description=(
            "Python code defining a compute_test_statistic(time, species_dict) function. "
            "Arguments: time (1D numpy array of timepoints), species_dict (dict mapping "
            "species names from required_species to 1D numpy arrays of values at each timepoint). "
            "Must return a scalar float value (the computed test statistic)."
        )
    )


class TestStatisticEstimates(BaseModel):
    """Test statistic estimates with structured inputs and derivation."""

    inputs: List[Input] = Field(description="List of inputs used in derivation")
    derivation_code: str = Field(
        description=(
            "Python code defining a derive_distribution(inputs, ureg) function. "
            "inputs is a dict mapping input names to Pint Quantities. "
            "Access values like: inputs['concentration'] (already a Pint Quantity). "
            "Must return dict with Pint Quantities: median_stat, iqr_stat, "
            "ci95_stat ([lower, upper])."
        )
    )
    median: float = Field(description="Median value")
    iqr: float = Field(description="Interquartile range")
    ci95: List[float] = Field(description="95% confidence interval [lower, upper]")
    units: str = Field(description="Units of the test statistic")
    key_assumptions: List[KeyAssumption] = Field(
        description="List of key assumptions with numbers and text"
    )


class ValidationWeights(BaseModel):
    """Validation weights for test statistics."""

    species_match: WeightScore
    system_match: WeightScore
    overall_confidence: WeightScore
    indication_match: WeightScore
    regimen_match: WeightScore
    biomarker_population_match: WeightScore
    stage_burden_match: WeightScore


class TestStatisticHeaders(BaseModel):
    """
    Header fields for test statistic files.

    These are metadata about the file itself (not generated by LLM):
    - What test statistic is being estimated
    - Which cancer type, scenario, and model context
    - User-provided model output code and expected units
    - When and how it was derived
    """

    schema_version: str = Field(description="Schema version (e.g., 'v2')")
    test_statistic_id: str = Field(description="Unique test statistic identifier")
    cancer_type: str = Field(description="Cancer type (e.g., 'PDAC')")
    output_unit: str = Field(description="Expected output unit (Pint-parseable string)")
    model_output_code: str = Field(description="User-provided compute_test_statistic function code")
    scenario_context: dict = Field(description="Scenario context (dosing, timing, etc.)")
    required_species: List[str] = Field(description="Required model output species")
    derived_species_description: str = Field(description="Description of derived test statistic")
    tags: List[str] = Field(default_factory=list, description="Metadata tags")


class TestStatistic(BaseModel):
    """
    Complete test statistic generated by LLM.

    Excludes header fields that are added during unpacking:
    - schema_version, test_statistic_id, cancer_type
    - output_unit, model_output_code (user-provided)
    - scenario_context, model_context, tags
    - required_species, derived_species_description

    Note: model_output_code is now a header field (user-provided during CSV enrichment),
    not LLM-generated. The LLM focuses on literature extraction for derivation_code.
    """

    test_statistic_definition: str = Field(
        description="Mathematical definition of the test statistic"
    )
    study_overview: str = Field(
        description="High-level biological context (WHAT and WHY) in 1-2 sentences"
    )
    study_design: str = Field(description="Concrete experimental details (HOW) in 1-2 sentences")
    test_statistic_estimates: TestStatisticEstimates = Field(
        description="Test statistic estimates with inputs and derivation"
    )
    derivation_explanation: str = Field(
        description="Step-by-step explanation of derivation code with assumption justifications"
    )
    key_study_limitations: str = Field(
        description="Important limitations and their impact on reliability"
    )
    primary_data_sources: List[Source] = Field(
        description="Primary data sources (original measurements)"
    )
    secondary_data_sources: List[SecondarySource] = Field(
        description="Secondary data sources (reference values, constants)"
    )
    validation_weights: ValidationWeights = Field(description="Validation weights")

    @classmethod
    def get_header_fields(cls) -> set[str]:
        """Get set of field names that are headers (from TestStatisticHeaders)."""
        return set(TestStatisticHeaders.model_fields.keys())

    def split(self) -> tuple[TestStatisticHeaders, dict]:
        """
        Split into headers and content.

        Returns:
            Tuple of (headers_model, content_dict)
        """
        header_fields = self.get_header_fields()
        all_data = self.model_dump()

        # Extract headers
        header_data = {k: v for k, v in all_data.items() if k in header_fields}
        headers = TestStatisticHeaders(**header_data)

        # Extract content
        content = {k: v for k, v in all_data.items() if k not in header_fields}

        return headers, content

    @classmethod
    def from_split(cls, headers: TestStatisticHeaders, content: dict) -> "TestStatistic":
        """
        Create TestStatistic from headers and content.

        Args:
            headers: TestStatisticHeaders instance
            content: Content dictionary (LLM-generated fields)

        Returns:
            Complete TestStatistic instance
        """
        return cls(**{**headers.model_dump(), **content})


# ============================================================================
# Model Registry (Maps complete models to their header models)
# ============================================================================


class ModelRegistry:
    """
    Central registry mapping complete models to their header models.

    This allows HeaderManager to work generically with any registered model type.
    """

    _registry: dict[type[BaseModel], type[BaseModel]] = {
        ParameterMetadata: ParameterHeaders,
        TestStatistic: TestStatisticHeaders,
        CalibrationTarget: CalibrationTargetHeaders,
    }

    @classmethod
    def get_header_model(cls, model_class: type[BaseModel]) -> type[BaseModel]:
        """
        Get the header model class for a complete model class.

        Args:
            model_class: Complete model class (e.g., ParameterMetadata)

        Returns:
            Header model class (e.g., ParameterHeaders)

        Raises:
            KeyError: If model_class is not registered
        """
        if model_class not in cls._registry:
            raise KeyError(
                f"Model {model_class.__name__} not registered. "
                f"Available models: {list(cls._registry.keys())}"
            )
        return cls._registry[model_class]

    @classmethod
    def register(cls, model_class: type[BaseModel], header_class: type[BaseModel]) -> None:
        """
        Register a new model and its header class.

        Args:
            model_class: Complete model class
            header_class: Corresponding header model class
        """
        cls._registry[model_class] = header_class

    @classmethod
    def is_registered(cls, model_class: type[BaseModel]) -> bool:
        """Check if a model class is registered."""
        return model_class in cls._registry
