#!/usr/bin/env python3
"""
Pydantic models for Calibration Targets.

Calibration targets are raw observables extracted from literature, used to calibrate
QSP model parameters via Bayesian inference. Each observable has an experimental
context that may differ from the model context, requiring formal mismatch handling.

See docs/calibration_target_design.md for full specification.
"""

import ast
from enum import Enum
from typing import List, Optional, Union

import numpy as np
from pydantic import BaseModel, Field, ValidationInfo, field_validator, model_validator

# Import from calibration submodules
from qsp_llm_workflows.core.calibration.exceptions import (
    ArrayLengthError,
    CalibrationTargetValidationError,
    CodeStructureError,
    CodeSyntaxError,
    ComputedValueMismatchError,
    ControlCharacterError,
    DimensionalityMismatchError,
    DOIResolutionError,
    HardcodedConstantError,
    MissingUnitsError,
    PaperTitleMismatchError,
    ReturnStructureError,
    ScaleMismatchError,
    ScalarReturnError,
    SnippetValueMismatchError,
    SourceRefError,
    SpeciesNotFoundError,
    UnitConversionError,
)
from qsp_llm_workflows.core.calibration.experimental_context import ExperimentalContext
from qsp_llm_workflows.core.calibration.observable import Observable
from qsp_llm_workflows.core.calibration.scenario import Scenario
from qsp_llm_workflows.core.calibration.shared_models import (
    EstimateInput,
    ModelingAssumption,
    SecondarySource,
    Source,
)
from qsp_llm_workflows.core.calibration.validators import (
    check_value_in_text,
    create_mock_species,
    fuzzy_match,
    get_typical_species_value,
    resolve_doi,
)


# ============================================================================
# Calibration Target
# ============================================================================


class CalibrationTargetFooters(BaseModel):
    """
    Footer fields for calibration target files.

    These are metadata about the file itself (not generated by LLM):
    - What observable is being tracked
    - Which cancer type
    - When and how it was derived
    """

    calibration_target_id: str = Field(description="Unique calibration target identifier")
    cancer_type: str = Field(description="Cancer type (e.g., 'PDAC')")
    tags: List[str] = Field(default_factory=list, description="Metadata tags")
    derivation_id: Optional[str] = Field(None, description="Unique derivation identifier")
    derivation_timestamp: Optional[str] = Field(None, description="ISO timestamp of derivation")


class IndexType(str, Enum):
    """Type of index dimension for vector-valued calibration targets."""

    TIME = "time"  # Time-course data (e.g., measurements at Day 0, 7, 14)
    DOSE = "dose"  # Dose-response data (e.g., drug concentrations)
    RATIO = "ratio"  # Ratio-based index (e.g., E:T ratios)
    CONCENTRATION = "concentration"  # Concentration series
    OTHER = "other"  # Other index types


class CalibrationTargetEstimates(BaseModel):
    """
    Calibration target estimates with structured inputs and derivation.

    Supports both scalar and vector-valued outputs:
    - Scalar: Single measurement → length-1 lists (median=[42.0], ci95=[[37.0, 47.0]])
    - Vector: Multi-point data → lists matching index_values length

    Vector-valued outputs are indexed by index_values (e.g., time points, doses).
    """

    median: List[float] = Field(
        description=(
            "COMPUTED median value(s) from distribution_code. "
            "Length-1 list for scalar data, or list matching index_values length for vector data."
        )
    )
    ci95: List[List[float]] = Field(
        description=(
            "COMPUTED 95% confidence intervals from distribution_code. "
            "List of [lower, upper] pairs. Length-1 for scalar data ([[lo, hi]]), "
            "or matching index_values length for vector data."
        )
    )
    units: str = Field(description="Units of the observable (Pint-parseable)")

    # Sample size metadata
    sample_size: Union[int, List[int]] = Field(
        description=(
            "Sample size (n) for the measurement. Critical for uncertainty quantification "
            "and pooling across studies. Single int for scalar data or same n for all index "
            "points. List[int] for different sample sizes at each index point (must match "
            "index_values length)."
        )
    )
    sample_size_rationale: str = Field(
        description=(
            "Explanation of how sample_size was determined. Document the source "
            "(e.g., 'n=5 per group stated in Methods section', 'n inferred from "
            "figure error bars using SEM formula', 'n estimated as typical for this study type')."
        )
    )

    # Index dimension for vector-valued data
    index_values: Optional[List[float]] = Field(
        None,
        description=(
            "Index values for vector-valued data (e.g., [0, 24, 48, 72] for time points). "
            "None for scalar data. Vector-valued inputs and outputs must match this length."
        ),
    )
    index_unit: Optional[str] = Field(
        None,
        description="Units for index_values (e.g., 'hour', 'day', 'nanomolar'). Required if index_values provided.",
    )
    index_type: Optional[IndexType] = Field(
        None,
        description="Type of index dimension. Required if index_values provided.",
    )

    inputs: List[EstimateInput] = Field(
        description=(
            "List of literature-extracted inputs used in distribution_code derivation. "
            "These are the VALUES REPORTED IN THE PAPER (mean, SD, median, IQR, trajectories, etc.) "
            "that are used to DERIVE the distribution via Monte Carlo. "
            "Inputs can be scalar (broadcast to all index points) or vector-valued (same length as index_values).\n\n"
            "NOTE: For inputs used in submodel or observable code, use submodel.inputs or observable.inputs instead."
        )
    )
    assumptions: List[ModelingAssumption] = Field(
        default_factory=list,
        description=(
            "List of modeling assumptions used in derivation. "
            "These are values NOT from the paper but needed for computation (e.g., n_mc_samples, "
            "assumed_cv when not reported). Each must have a rationale field explaining the choice."
        ),
    )
    distribution_code: str = Field(
        description=(
            "Python code defining a derive_distribution(inputs, ureg) function.\n"
            "inputs is a dict mapping input names to Pint Quantities (scalar or array).\n"
            "Must return dict with Pint Quantities:\n"
            "  - median_obs: array of medians (length matching index_values, or length 1 for scalar)\n"
            "  - ci95_obs: list of [lower, upper] pairs (same length)\n\n"
            "For scalar data, return length-1 arrays.\n"
            "For vector data, return arrays matching index_values length.\n\n"
            "Example (scalar - single measurement):\n"
            "def derive_distribution(inputs, ureg):\n"
            "    import numpy as np\n"
            "    mean = inputs['cd8_density_mean'].magnitude\n"
            "    sd = inputs['cd8_density_sd'].magnitude\n"
            "    units = inputs['cd8_density_mean'].units\n"
            "    samples = np.random.normal(mean, sd, 10000)\n"
            "    return {\n"
            "        'median_obs': np.array([np.median(samples)]) * units,\n"
            "        'ci95_obs': [[np.percentile(samples, 2.5) * units, np.percentile(samples, 97.5) * units]]\n"
            "    }\n\n"
            "Example (vector - time-course data):\n"
            "def derive_distribution(inputs, ureg):\n"
            "    import numpy as np\n"
            "    means = inputs['cd8_density_mean'].magnitude  # array\n"
            "    sds = inputs['cd8_density_sd'].magnitude  # array\n"
            "    units = inputs['cd8_density_mean'].units\n"
            "    n_points = len(means)\n"
            "    medians, ci95s = [], []\n"
            "    for i in range(n_points):\n"
            "        samples = np.random.normal(means[i], sds[i], 10000)\n"
            "        medians.append(np.median(samples))\n"
            "        ci95s.append([np.percentile(samples, 2.5) * units, np.percentile(samples, 97.5) * units])\n"
            "    return {\n"
            "        'median_obs': np.array(medians) * units,\n"
            "        'ci95_obs': ci95s\n"
            "    }"
        )
    )

    @field_validator("sample_size")
    @classmethod
    def validate_sample_size_positive(cls, v: Union[int, List[int]]) -> Union[int, List[int]]:
        """Validate sample size is at least 1."""
        if isinstance(v, list):
            for i, n in enumerate(v):
                if n < 1:
                    raise ValueError(f"sample_size[{i}] must be at least 1, got {n}")
        else:
            if v < 1:
                raise ValueError(f"sample_size must be at least 1, got {v}")
        return v

    @model_validator(mode="after")
    def validate_output_lengths_match(self) -> "CalibrationTargetEstimates":
        """Validator: Ensure median and ci95 have the same length."""
        n_median = len(self.median)
        n_ci95 = len(self.ci95)

        if n_median != n_ci95:
            raise ValueError(
                f"Output array lengths must match: median has {n_median}, ci95 has {n_ci95}"
            )

        # Check ci95 inner structure
        for i, ci in enumerate(self.ci95):
            if len(ci) != 2:
                raise ValueError(f"ci95[{i}] must be [lower, upper] pair, got {len(ci)} elements")

        return self

    @model_validator(mode="after")
    def validate_index_fields_consistent(self) -> "CalibrationTargetEstimates":
        """Validator: Ensure index_* fields are all present or all absent."""
        has_values = self.index_values is not None
        has_unit = self.index_unit is not None
        has_type = self.index_type is not None

        if has_values:
            if not has_unit:
                raise ValueError("index_unit is required when index_values is provided")
            if not has_type:
                raise ValueError("index_type is required when index_values is provided")

            # Check that output length matches index_values length
            # Type narrowing: we know index_values is not None here
            assert self.index_values is not None  # for type checker
            n_index = len(self.index_values)
            n_output = len(self.median)
            if n_output != n_index:
                raise ValueError(
                    f"Output length ({n_output}) must match index_values length ({n_index})"
                )
        else:
            # Scalar case: must have length 1
            if len(self.median) != 1:
                raise ValueError(
                    f"For scalar data (no index_values), outputs must have length 1, "
                    f"got {len(self.median)}"
                )

        return self

    @model_validator(mode="after")
    def validate_vector_input_lengths(self) -> "CalibrationTargetEstimates":
        """Validator: Ensure vector-valued inputs and assumptions match index_values length."""
        if self.index_values is None:
            return self  # Scalar case, skip

        n_index = len(self.index_values)

        # Check literature inputs
        for inp in self.inputs:
            if isinstance(inp.value, list):
                if len(inp.value) != n_index:
                    raise ValueError(
                        f"Vector input '{inp.name}' has length {len(inp.value)}, "
                        f"but index_values has length {n_index}. "
                        f"Vector inputs must match index_values length."
                    )

        # Check assumptions
        for assumption in self.assumptions:
            if isinstance(assumption.value, list):
                if len(assumption.value) != n_index:
                    raise ValueError(
                        f"Vector assumption '{assumption.name}' has length {len(assumption.value)}, "
                        f"but index_values has length {n_index}. "
                        f"Vector assumptions must match index_values length."
                    )

        return self

    @model_validator(mode="after")
    def validate_sample_size_length(self) -> "CalibrationTargetEstimates":
        """Validator: Ensure vector sample_size matches index_values length."""
        if isinstance(self.sample_size, list):
            if self.index_values is None:
                raise ValueError(
                    "Vector sample_size requires index_values. " "Use a single int for scalar data."
                )
            if len(self.sample_size) != len(self.index_values):
                raise ValueError(
                    f"sample_size length ({len(self.sample_size)}) must match "
                    f"index_values length ({len(self.index_values)})"
                )
        return self


class CalibrationTarget(BaseModel):
    """
    A calibration target: a raw observable extracted from literature.

    Used to calibrate QSP model parameters via Bayesian inference.

    Excludes header fields that are added during unpacking:
    - calibration_target_id, cancer_type
    - tags, derivation_id, derivation_timestamp
    """

    # --- Observable fields (LLM-generated) ---
    calibration_target_estimates: CalibrationTargetEstimates = Field(
        description="Observable estimates with inputs and derivation"
    )

    # ========================================================================
    # Field definitions
    # ========================================================================

    # --- Observable specification (LLM-generated) ---
    observable: Observable = Field(
        description=(
            "How to compute the experimental observable from full model species. "
            "Defines the code that transforms model output to match literature measurements."
        )
    )

    # --- Experimental context (LLM-generated, grouped for distance calculations) ---
    experimental_context: ExperimentalContext = Field(
        description="Experimental context of the observable"
    )

    # --- Scenario (optional, for intervention tracking) ---
    scenario: Optional[Scenario] = Field(
        default=None,
        description=(
            "Experimental scenario with interventions. Optional - can be omitted if "
            "no interventions or if intervention details are captured in rationale."
        ),
    )

    # --- Consolidated narrative (LLM-generated) ---
    rationale: str = Field(
        description=(
            "Single consolidated explanation covering:\n"
            "- What observable is being measured and why it's relevant\n"
            "- How the experimental data maps to model species/parameters\n"
            "- Key assumptions made in the derivation\n"
            "- Any interventions or experimental conditions\n\n"
            "This replaces: description, study_overview, study_design, "
            "derivation_explanation, scenario.description, and key_assumptions."
        )
    )

    caveats: List[str] = Field(
        default_factory=list,
        description=(
            "List of limitations, assumptions, or caveats as simple strings.\n"
            "Examples:\n"
            "- 'Values estimated from figures, not tabulated'\n"
            "- 'Single-center cohort (n~15), limited generalizability'\n"
            "- 'Bulk CD3+ assay, not CD8-specific'\n"
            "- 'Normal distribution assumed for positive-only data'"
        ),
    )

    # --- Sources (LLM-generated) ---
    primary_data_source: Source = Field(
        description="Primary data source (the paper where this observable was measured)"
    )
    secondary_data_sources: List[SecondarySource] = Field(
        default_factory=list, description="Secondary data sources (reference values, constants)"
    )

    @classmethod
    def get_header_fields(cls) -> set[str]:
        """Get set of field names that are headers (from CalibrationTargetFooters)."""
        return set(CalibrationTargetFooters.model_fields.keys())

    def split(self) -> tuple[CalibrationTargetFooters, dict]:
        """
        Split into headers and content.

        Returns:
            Tuple of (headers_model, content_dict)
        """
        header_fields = self.get_header_fields()
        all_data = self.model_dump()

        # Extract headers
        header_data = {k: v for k, v in all_data.items() if k in header_fields}
        headers = CalibrationTargetFooters(**header_data)

        # Extract content
        content = {k: v for k, v in all_data.items() if k not in header_fields}

        return headers, content

    @classmethod
    def from_split(cls, headers: CalibrationTargetFooters, content: dict) -> "CalibrationTarget":
        """
        Create CalibrationTarget from headers and content.

        Args:
            headers: CalibrationTargetFooters instance
            content: Content dictionary (LLM-generated fields)

        Returns:
            Complete CalibrationTarget instance
        """
        return cls(**{**headers.model_dump(), **content})

    @model_validator(mode="after")
    def validate_doi_resolution(self) -> "CalibrationTarget":
        """Validator: Check that primary DOI resolves via CrossRef."""
        if self.primary_data_source.doi:
            metadata = resolve_doi(self.primary_data_source.doi)
            if metadata is None:
                raise DOIResolutionError(
                    f"DOI '{self.primary_data_source.doi}' failed to resolve via CrossRef. "
                    "Verify the DOI exists and is correctly formatted (e.g., '10.1234/journal.2023.123'). "
                    "Search for the paper on Google Scholar or PubMed to find the correct DOI."
                )
        return self

    @model_validator(mode="after")
    def validate_title_match(self) -> "CalibrationTarget":
        """Validator: Check that paper title matches CrossRef metadata."""
        if self.primary_data_source.doi:
            metadata = resolve_doi(self.primary_data_source.doi)
            if metadata:
                crossref_title = metadata.get("title", "")
                if not fuzzy_match(crossref_title, self.primary_data_source.title, threshold=0.75):
                    raise PaperTitleMismatchError(
                        f"Paper title mismatch:\n"
                        f"  CrossRef: '{crossref_title}'\n"
                        f"  Provided: '{self.primary_data_source.title}'\n"
                        f"Use the exact title from the DOI. Copy the title from CrossRef or the paper itself."
                    )
        return self

    @model_validator(mode="after")
    def validate_secondary_doi_resolution(self) -> "CalibrationTarget":
        """Validator: Check that secondary source DOIs resolve via CrossRef.

        Secondary sources use doi_or_url field which can be a DOI or URL.
        Only validates entries that look like DOIs (start with '10.').
        """
        for source in self.secondary_data_sources:
            doi_or_url = source.doi_or_url
            if not doi_or_url:
                continue

            # Check if it looks like a DOI (starts with 10. or contains doi.org)
            is_doi = doi_or_url.startswith("10.") or "doi.org/10." in doi_or_url

            if is_doi:
                metadata = resolve_doi(doi_or_url)
                if metadata is None:
                    raise DOIResolutionError(
                        f"Secondary source '{source.source_tag}' has DOI '{doi_or_url}' "
                        f"that failed to resolve via CrossRef.\n"
                        f"Verify the DOI exists and is correctly formatted (e.g., '10.1234/journal.2023.123').\n"
                        f"If this is a URL (not a DOI), ensure it doesn't start with '10.' or contain 'doi.org'."
                    )
        return self

    @model_validator(mode="after")
    def validate_secondary_title_match(self) -> "CalibrationTarget":
        """Validator: Check that secondary source titles match CrossRef metadata.

        Only validates entries with DOIs (not URLs).
        """
        for source in self.secondary_data_sources:
            doi_or_url = source.doi_or_url
            if not doi_or_url:
                continue

            # Check if it looks like a DOI
            is_doi = doi_or_url.startswith("10.") or "doi.org/10." in doi_or_url

            if is_doi:
                metadata = resolve_doi(doi_or_url)
                if metadata:
                    crossref_title = metadata.get("title", "")
                    if not fuzzy_match(crossref_title, source.title, threshold=0.75):
                        raise PaperTitleMismatchError(
                            f"Secondary source '{source.source_tag}' title mismatch:\n"
                            f"  CrossRef: '{crossref_title}'\n"
                            f"  Provided: '{source.title}'\n"
                            f"Use the exact title from the DOI. Copy the title from CrossRef or the paper itself."
                        )
        return self

    @model_validator(mode="after")
    def validate_observable_code_units(self, info: ValidationInfo) -> "CalibrationTarget":
        """
        Validator: Check that observable code executes and returns correct units.

        Requires context:
            species_units: Dict mapping species names to unit strings (from species_units.json)
        """
        # Skip for IsolatedSystemTarget (uses submodel.observable instead)
        if type(self).__name__ == "IsolatedSystemTarget":
            return self

        from qsp_llm_workflows.core.unit_registry import ureg
        from qsp_llm_workflows.core.calibration.code_validator import (
            CodeType,
            validate_code_block,
        )
        import pint

        # Get species_units from context
        if not info.context:
            raise ValueError(
                "Validation context is required. Pass context={'species_units': {...}}"
            )
        species_units = info.context["species_units"]

        # Use CodeValidator for syntax and signature checks
        result = validate_code_block(
            self.observable.code,
            CodeType.OBSERVABLE,
            check_hardcoded=False,  # Handled by separate validator
            check_execution=False,  # We do custom execution below
        )

        if not result.passed:
            errors = result.get_errors()
            if errors:
                first_error = errors[0]
                if first_error.category == "syntax":
                    raise CodeSyntaxError(
                        f"observable.code has syntax error: {first_error.message}"
                    )
                elif first_error.category == "signature":
                    raise CodeStructureError(first_error.message)
                else:
                    raise CodeStructureError(first_error.message)

        # Execute with mock data
        try:
            # Create mock time array
            mock_time = np.linspace(0, 14, 100) * ureg.day

            # Create mock species from actual model (with matching length)
            mock_species = create_mock_species(species_units, ureg, n_timepoints=len(mock_time))

            # Build constants dict from observable.constants
            constants = {}
            for const in self.observable.constants:
                constants[const.name] = const.value * ureg(const.units)

            # Execute function
            local_scope = {"ureg": ureg, "np": np}
            exec(self.observable.code, local_scope)
            compute_fn = local_scope["compute_observable"]

            result = compute_fn(mock_time, mock_species, constants, ureg)

            # Check result has units
            if not hasattr(result, "units"):
                raise MissingUnitsError("Function must return a Pint Quantity with units")

            # Check dimensionality matches calibration target units
            expected_quantity = 1.0 * ureg(self.calibration_target_estimates.units)
            if result.dimensionality != expected_quantity.dimensionality:
                raise DimensionalityMismatchError(
                    f"Observable code unit dimensionality mismatch:\n"
                    f"  Expected: {self.calibration_target_estimates.units} ({expected_quantity.dimensionality})\n"
                    f"  Got: {result.units} ({result.dimensionality})"
                )

            # Check result has same length as time series (no time indexing)
            if hasattr(result, "magnitude"):
                result_magnitude = result.magnitude
                # Handle both scalar and array results
                if np.isscalar(result_magnitude):
                    raise ScalarReturnError(
                        f"Observable code returned a scalar, but should return an array with same length as time series.\n"
                        f"  Expected length: {len(mock_time)}\n"
                        f"  Got: scalar value\n"
                        f"Do NOT use time indexing (e.g., species[-1] or species[0]) in observable code.\n"
                        f"Compute the observable over the entire time series."
                    )
                elif len(result_magnitude) != len(mock_time):
                    raise ArrayLengthError(
                        f"Observable code returned array with wrong length:\n"
                        f"  Expected: {len(mock_time)} (same as time series)\n"
                        f"  Got: {len(result_magnitude)}\n"
                        f"Do NOT use time indexing. Compute over entire time series."
                    )

        except (
            pint.DimensionalityError,
            pint.UndefinedUnitError,
            pint.OffsetUnitCalculusError,
        ) as e:
            # Wrap Pint unit errors in our custom exception
            raise UnitConversionError(
                f"Observable code has unit error: {str(e)}\n"
                f"Check that all unit operations are dimensionally consistent."
            ) from e
        except CalibrationTargetValidationError:
            # Re-raise all our custom validation errors
            raise
        except Exception:
            # Other errors might be from complex logic or missing species
            # Be lenient - actual execution will catch these
            pass

        return self

    @model_validator(mode="after")
    def validate_input_values_in_snippets(self) -> "CalibrationTarget":
        """Validator: Check that input values appear in their value_snippet.

        Ensures data integrity by verifying that extracted values can be found
        in the source text. Handles multiple numeric formats (decimal, scientific,
        percentage, rounded variations).

        Checks inputs in:
        - calibration_target_estimates.inputs (EstimateInput)
        - observable.inputs (SubmodelInput)

        Raises SnippetValueMismatchError if a value is not found in its snippet.
        """

        def check_inputs(inputs, location_prefix: str):
            """Helper to check value_snippet for a list of inputs."""
            for inp in inputs:
                value = inp.value
                snippet = inp.value_snippet

                if not snippet:
                    continue

                # Handle both scalar and vector-valued inputs
                values_to_check = [value] if not isinstance(value, list) else value

                missing_values = []
                for val in values_to_check:
                    if not check_value_in_text(snippet, val):
                        missing_values.append(val)

                if missing_values:
                    raise SnippetValueMismatchError(
                        f"{location_prefix} input '{inp.name}' has value(s) not found in value_snippet.\n"
                        f"  Missing values: {missing_values}\n"
                        f"  Snippet: '{snippet[:200]}{'...' if len(snippet) > 200 else ''}'\n"
                        f"The value_snippet must contain the exact values extracted from the paper.\n"
                        f"Check for:\n"
                        f"  - Typos in the extracted value\n"
                        f"  - Different numeric format in the paper (e.g., '2.5×10⁻³' vs '0.0025')\n"
                        f"  - Value reported in different units that need conversion\n"
                        f"  - Snippet truncated before the value appears"
                    )

        # Check calibration_target_estimates.inputs
        check_inputs(self.calibration_target_estimates.inputs, "calibration_target_estimates")

        # Check observable.inputs (if present and not IsolatedSystemTarget)
        if type(self).__name__ != "IsolatedSystemTarget" and self.observable.inputs:
            check_inputs(self.observable.inputs, "observable")

        return self

    @model_validator(mode="after")
    def validate_derivation_code(self) -> "CalibrationTarget":
        """
        Validator: Check that derivation_code executes, returns correct structure and units,
        and computed values match reported values (element-wise for vector data).
        """
        from qsp_llm_workflows.core.unit_registry import ureg
        from qsp_llm_workflows.core.calibration.code_validator import (
            CodeType,
            validate_code_block,
        )

        # Use CodeValidator for syntax and signature checks
        result = validate_code_block(
            self.calibration_target_estimates.distribution_code,
            CodeType.DISTRIBUTION,
            check_hardcoded=True,  # Check for hardcoded constants with units
            check_execution=False,  # We do custom execution below
        )

        if not result.passed:
            errors = result.get_errors()
            if errors:
                first_error = errors[0]
                if first_error.category == "syntax":
                    raise CodeSyntaxError(
                        f"distribution_code has syntax error: {first_error.message}"
                    )
                elif first_error.category == "signature":
                    raise CodeStructureError(first_error.message)
                else:
                    raise CodeStructureError(first_error.message)

        # Execute with mock inputs to test structure and units
        try:
            # Create mock inputs dict with Pint quantities
            # Merge both literature inputs and modeling assumptions into a single dict
            mock_inputs = {}
            # Add literature inputs
            for inp in self.calibration_target_estimates.inputs:
                if isinstance(inp.value, list):
                    mock_inputs[inp.name] = np.array(inp.value) * ureg(inp.units)
                else:
                    mock_inputs[inp.name] = inp.value * ureg(inp.units)
            # Add modeling assumptions
            for assumption in self.calibration_target_estimates.assumptions:
                if isinstance(assumption.value, list):
                    mock_inputs[assumption.name] = np.array(assumption.value) * ureg(
                        assumption.units
                    )
                else:
                    mock_inputs[assumption.name] = assumption.value * ureg(assumption.units)

            # Execute function
            local_scope = {"ureg": ureg, "np": np}
            exec(self.calibration_target_estimates.distribution_code, local_scope)
            derive_fn = local_scope["derive_distribution"]

            result = derive_fn(mock_inputs, ureg)

            # Check result is dict with required keys
            if not isinstance(result, dict):
                raise ReturnStructureError("Function must return a dict")

            required_keys = {"median_obs", "ci95_obs"}
            if not required_keys.issubset(result.keys()):
                raise ReturnStructureError(
                    f"Function must return dict with keys: {required_keys}. Got: {result.keys()}"
                )

            # Check median_obs has units
            if not hasattr(result["median_obs"], "units"):
                raise MissingUnitsError("Result['median_obs'] must be a Pint Quantity with units")

            # Check dimensionality matches expected units
            expected_quantity = 1.0 * ureg(self.calibration_target_estimates.units)

            # Check median
            if result["median_obs"].dimensionality != expected_quantity.dimensionality:
                raise DimensionalityMismatchError(
                    f"median_obs unit dimensionality mismatch:\n"
                    f"  Expected: {self.calibration_target_estimates.units} ({expected_quantity.dimensionality})\n"
                    f"  Got: {result['median_obs'].units} ({result['median_obs'].dimensionality})"
                )

            # Check ci95_obs is list of [lower, upper] pairs matching expected length
            n_expected = len(self.calibration_target_estimates.median)
            ci95_result = result["ci95_obs"]

            if not hasattr(ci95_result, "__len__") or len(ci95_result) != n_expected:
                raise ReturnStructureError(
                    f"ci95_obs must be a list of {n_expected} [lower, upper] pairs, "
                    f"got {len(ci95_result) if hasattr(ci95_result, '__len__') else 'non-list'}"
                )

            # Check each ci95 pair
            for i, ci_pair in enumerate(ci95_result):
                if not hasattr(ci_pair, "__len__") or len(ci_pair) != 2:
                    raise ReturnStructureError(
                        f"ci95_obs[{i}] must be [lower, upper] pair, "
                        f"got {len(ci_pair) if hasattr(ci_pair, '__len__') else 'non-list'} elements"
                    )

            # Convert computed values to expected units for comparison
            median_computed = result["median_obs"].to(self.calibration_target_estimates.units)

            # Get reported values (now lists)
            median_reported = self.calibration_target_estimates.median
            ci95_reported = self.calibration_target_estimates.ci95

            # Use relative tolerance of 1% for comparison
            rel_tol = 0.01

            # Handle array magnitudes
            median_mag = np.atleast_1d(median_computed.magnitude)

            # Element-wise comparison for median
            for i in range(len(median_reported)):
                if abs(median_mag[i] - median_reported[i]) > rel_tol * abs(median_reported[i]):
                    raise ComputedValueMismatchError(
                        f"Computed median[{i}] ({median_mag[i]:.4g}) does not match "
                        f"reported median[{i}] ({median_reported[i]:.4g}) within 1% tolerance"
                    )

            # Element-wise comparison for CI95
            for i in range(len(ci95_reported)):
                ci_computed = ci95_result[i]
                ci_rep = ci95_reported[i]

                # Get magnitudes (handle Pint quantities)
                lo_computed = (
                    ci_computed[0].magnitude
                    if hasattr(ci_computed[0], "magnitude")
                    else ci_computed[0]
                )
                hi_computed = (
                    ci_computed[1].magnitude
                    if hasattr(ci_computed[1], "magnitude")
                    else ci_computed[1]
                )

                if abs(lo_computed - ci_rep[0]) > rel_tol * abs(ci_rep[0]):
                    raise ComputedValueMismatchError(
                        f"Computed CI95[{i}] lower ({lo_computed:.4g}) does not match "
                        f"reported CI95[{i}] lower ({ci_rep[0]:.4g}) within 1% tolerance"
                    )

                if abs(hi_computed - ci_rep[1]) > rel_tol * abs(ci_rep[1]):
                    raise ComputedValueMismatchError(
                        f"Computed CI95[{i}] upper ({hi_computed:.4g}) does not match "
                        f"reported CI95[{i}] upper ({ci_rep[1]:.4g}) within 1% tolerance"
                    )

        except CalibrationTargetValidationError:
            # Re-raise all our custom validation errors
            raise
        except Exception as e:
            # Other execution errors - wrap in generic validation error
            raise CalibrationTargetValidationError(f"Error executing derivation_code: {e}") from e

        return self

    @model_validator(mode="after")
    def validate_source_refs(self) -> "CalibrationTarget":
        """Validator: Check all source_refs in inputs point to defined sources.

        Checks source_refs in:
        - calibration_target_estimates.inputs (EstimateInput)
        - observable.inputs (SubmodelInput)
        """
        # Build set of valid source tags from literature sources
        valid_tags = {self.primary_data_source.source_tag}
        valid_tags.update(s.source_tag for s in self.secondary_data_sources)

        def check_refs(inputs, location_prefix: str):
            """Helper to check source_refs for a list of inputs."""
            for inp in inputs:
                if inp.source_ref not in valid_tags:
                    raise SourceRefError(
                        f"{location_prefix} input '{inp.name}' has source_ref '{inp.source_ref}' which is not defined.\n"
                        f"Valid source tags: {sorted(valid_tags)}\n"
                        f"Add the source to primary_data_source or secondary_data_sources.\n"
                        f"For values not from literature, use the 'assumptions' field instead."
                    )

        # Check calibration_target_estimates.inputs
        check_refs(self.calibration_target_estimates.inputs, "calibration_target_estimates")

        # Check observable.inputs (if present and not IsolatedSystemTarget)
        if type(self).__name__ != "IsolatedSystemTarget" and self.observable.inputs:
            check_refs(self.observable.inputs, "observable")

        return self

    @model_validator(mode="after")
    def validate_species_exist(self, info: ValidationInfo) -> "CalibrationTarget":
        """
        Validator: Check that observable.species exist in model.

        Requires context:
            species_units: Dict mapping species names to unit strings (from species_units.json)
        """
        # Skip for IsolatedSystemTarget (uses submodel.observable instead)
        if type(self).__name__ == "IsolatedSystemTarget":
            return self

        # Get species_units from context
        if not info.context:
            raise ValueError(
                "Validation context is required. Pass context={'species_units': {...}}"
            )
        species_units = info.context["species_units"]
        available_species = set(species_units.keys())

        # Check all observable species exist
        for species in self.observable.species:
            if species not in available_species:
                raise SpeciesNotFoundError(
                    f"observable.species '{species}' not found in model.\n"
                    f"Available species: {sorted(available_species)}\n"
                    f"Check species name format (should be compartment.species, e.g., 'V_T.C1', 'V_T.CD8')"
                )

        return self

    # DISABLED: Simplified measurement structure - executable code deferred to manual implementation
    # @model_validator(mode="after")
    # def validate_threshold_conversion_code(self, info: ValidationInfo) -> "CalibrationTarget":
    #     """Validator disabled for simplified measurement structure."""
    #     return self

    @model_validator(mode="after")
    def validate_clipping_suggests_lognormal(self) -> "CalibrationTarget":
        """
        Validator (WARNING): Check if distribution_code uses clipping.

        Clipping to avoid negative values suggests size/volume data that
        should use lognormal distribution instead of normal.
        """
        import warnings

        code = self.calibration_target_estimates.distribution_code

        # Check for clipping patterns
        clipping_patterns = ["np.clip", "np.maximum", "np.minimum", "max(0", "min("]
        if any(pattern in code for pattern in clipping_patterns):
            warnings.warn(
                "distribution_code uses clipping (np.clip/np.maximum/etc) to avoid negative values. "
                "This suggests size/volume/mass data that may be better modeled with a lognormal distribution. "
                "Normal distributions for positive-only data introduce bias when clipped. "
                "Consider converting mean±SD to lognormal parameters: "
                "μ_log = ln(mean²/√(mean²+sd²)), σ_log = √(ln(1+sd²/mean²))",
                UserWarning,
            )

        return self

    @model_validator(mode="after")
    def validate_large_variance_documented(self) -> "CalibrationTarget":
        """
        Validator (WARNING): Check if large variance is documented in limitations.

        CV > 50% suggests substantial variability that should be explained.
        Only applies to scalar inputs (vector inputs are checked per-element elsewhere).
        """
        import warnings

        # Find mean and SD/SE inputs (only scalar inputs)
        mean_input = None
        std_input = None

        for inp in self.calibration_target_estimates.inputs:
            # Skip vector-valued inputs for this check
            if isinstance(inp.value, list):
                continue

            name_lower = inp.name.lower()
            if "mean" in name_lower and mean_input is None:
                mean_input = inp
            if any(x in name_lower for x in ["sd", "std", "se", "stderr", "stdev"]):
                std_input = inp

        if mean_input and std_input:
            mean_val = mean_input.value
            std_val = std_input.value

            # Both must be scalar at this point (we skipped lists above)
            if not isinstance(mean_val, list) and not isinstance(std_val, list) and mean_val != 0:
                # Calculate CV (coefficient of variation)
                cv = abs(std_val / mean_val)

                if cv > 0.5:  # CV > 50%
                    # Check if caveats or rationale mention variance/uncertainty
                    caveats_text = " ".join(self.caveats).lower()
                    rationale_lower = self.rationale.lower()
                    combined_text = caveats_text + " " + rationale_lower
                    variance_keywords = [
                        "variance",
                        "variability",
                        "uncertain",
                        "cv",
                        "wide",
                        "heterogen",
                        "variation",
                        "spread",
                        "dispersion",
                    ]

                    if not any(keyword in combined_text for keyword in variance_keywords):
                        warnings.warn(
                            f"Large coefficient of variation (CV = {cv:.1%}) detected but not discussed in caveats. "
                            f"Consider adding a caveat explaining whether this reflects biological variability, "
                            f"measurement error, or heterogeneous population.",
                            UserWarning,
                        )

        return self

    @model_validator(mode="after")
    def validate_distribution_choice_for_size_data(self) -> "CalibrationTarget":
        """
        Validator (WARNING): Check if normal distribution used for size data.

        Size/volume/mass measurements are typically lognormal, not normal.
        """
        import warnings

        units = self.calibration_target_estimates.units.lower()
        code = self.calibration_target_estimates.distribution_code

        # Check if units suggest size/volume/mass
        size_units = ["meter", "liter", "gram", "cell", "mole", "molarity"]
        is_size_data = any(unit in units for unit in size_units) and units != "dimensionless"

        # Check if using normal distribution (but not lognormal)
        uses_normal = ("normal(" in code or "randn" in code) and "lognormal" not in code

        if is_size_data and uses_normal:
            warnings.warn(
                f"Using normal distribution for size/volume/mass data (units: {units}). "
                f"These measurements are typically lognormally distributed. "
                f"Normal distributions can produce non-physical negative values requiring clipping. "
                f"Consider using lognormal distribution instead.",
                UserWarning,
            )

        return self

    @model_validator(mode="after")
    def validate_conversion_factors_documented(self) -> "CalibrationTarget":
        """
        Validator (WARNING): Check that conversion factors are documented.

        Magic numbers in observable.code should be in observable.constants or rationale/caveats.
        """
        # Skip for IsolatedSystemTarget (uses submodel.observable instead)
        if type(self).__name__ == "IsolatedSystemTarget":
            return self

        import warnings

        # Universal constants to ignore (only truly fundamental values)
        UNIVERSAL_CONSTANTS = {
            # Basic integers
            0,
            1,
            2,
            3,
            4,
            # Mathematical constants
            np.pi,
            3.14159,
            3.141592653589793,
            np.e,
            2.71828,
            2.718281828459045,
            # Common fractions
            0.5,
            0.25,
            0.75,
            # Statistical percentiles (standard)
            2.5,
            25,
            50,
            75,
            97.5,
            0.025,
            0.25,
            0.5,
            0.75,
            0.975,
        }

        code = self.observable.code

        # Extract numeric literals from code
        try:
            tree = ast.parse(code)
            literals = []
            for node in ast.walk(tree):
                if isinstance(node, ast.Constant) and isinstance(node.value, (int, float)):
                    val = node.value
                    # Skip universal constants (with tolerance for floating point)
                    if not any(abs(val - c) < 1e-6 for c in UNIVERSAL_CONSTANTS):
                        literals.append(val)
        except SyntaxError:
            # If code doesn't parse, skip this check
            return self

        if literals:
            # Check if these appear in observable.constants or rationale/caveats
            constant_values: list[float] = [c.value for c in self.observable.constants]

            # Check rationale and caveats for documentation
            combined_text = self.rationale + " " + " ".join(self.caveats)

            undocumented = []
            for lit in literals:
                # Check if value appears in constants (with tolerance)
                in_constants = any(abs(lit - v) < 1e-6 for v in constant_values)
                # Check if value appears in rationale/caveats text
                in_text = str(lit) in combined_text or f"{lit:.0e}" in combined_text

                if not (in_constants or in_text):
                    undocumented.append(lit)

            if undocumented:
                warnings.warn(
                    f"observable.code contains numeric literals {undocumented} that may be conversion factors. "
                    f"Document these in observable.constants or explain in rationale. "
                    f"Examples: cell sizes (µm), cellularity fractions, density values, geometric conversion factors.",
                    UserWarning,
                )

        return self

    @model_validator(mode="after")
    def validate_inputs_used(self) -> "CalibrationTarget":
        """Validator: Warn if inputs/assumptions are defined but not used in distribution_code."""
        # Extract all names accessed from 'inputs' dict
        used_input_names = set()

        class InputAccessVisitor(ast.NodeVisitor):
            def visit_Subscript(self, node):
                # Look for inputs['name'] or inputs["name"]
                if isinstance(node.value, ast.Name) and node.value.id == "inputs":
                    if isinstance(node.slice, ast.Constant):
                        used_input_names.add(node.slice.value)
                self.generic_visit(node)

        # Parse distribution_code to find variable references
        try:
            tree = ast.parse(self.calibration_target_estimates.distribution_code)
            visitor = InputAccessVisitor()
            visitor.visit(tree)
        except SyntaxError:
            # Already caught by validate_derivation_code
            pass

        # Check which defined inputs/assumptions are not used in distribution_code
        # Both EstimateInputs and ModelingAssumptions are merged into the inputs dict
        defined_inputs = {inp.name for inp in self.calibration_target_estimates.inputs}
        defined_assumptions = {a.name for a in self.calibration_target_estimates.assumptions}
        all_defined = defined_inputs | defined_assumptions
        unused = all_defined - used_input_names

        if unused:
            # This is a warning, not an error - could be intentional
            import warnings

            warnings.warn(
                f"The following inputs/assumptions are defined but not used in distribution_code: {sorted(unused)}. "
                f"If these are not needed, consider removing them.",
                UserWarning,
            )

        return self

    @model_validator(mode="after")
    def validate_no_hardcoded_constants_in_observable_code(self) -> "CalibrationTarget":
        """
        Validator (ERROR): Flag hardcoded numbers with units in observable.code.

        Uses AST-based detection to find numeric constants multiplied by ureg units.

        All numeric constants with units must be declared in observable.constants
        and accessed via the constants dict. This prevents arbitrary magic numbers
        and forces explicit documentation of biological assumptions.

        Allowed inline numbers:
        - Small integers (0-5)
        - Common fractions (0.5, 0.25, 0.75)
        - Statistical percentiles (2.5, 25, 50, 75, 97.5)
        - Common conversion factors (100, 1000)
        """
        # Skip for IsolatedSystemTarget (uses submodel.observable instead)
        if type(self).__name__ == "IsolatedSystemTarget":
            return self

        from qsp_llm_workflows.core.calibration.code_validator import find_hardcoded_constants

        violations = find_hardcoded_constants(self.observable.code)

        if violations:
            violation_strs = [f"  • {v[0]} in '{v[3]}' (line {v[1]})" for v in violations[:5]]
            raise HardcodedConstantError(
                "Hardcoded numeric constants with units found in observable.code:\n"
                + "\n".join(violation_strs)
                + (f"\n  ... and {len(violations) - 5} more" if len(violations) > 5 else "")
                + "\n\nAll numeric constants with units must be declared in observable.constants "
                + "and accessed via the constants dict.\n"
                + "Example fix:\n"
                + "  1. Add to observable.constants:\n"
                + "     - name: area_per_cancer_cell\n"
                + "       value: 2.27e-4\n"
                + "       units: mm**2/cell\n"
                + "       biological_basis: 'Cancer cell diameter ~17 μm → area = π×(8.5 μm)²'\n"
                + "       source_ref: modeling_assumption\n"
                + "  2. Use in code: area_per_cell = constants['area_per_cancer_cell']"
            )

        return self

    @model_validator(mode="after")
    def validate_scale_consistency(self, info: ValidationInfo) -> "CalibrationTarget":
        """
        Validator: Check that observable.code output scale matches calibration target scale.

        Executes observable.code with mock species data spanning wide range and checks
        if output range is compatible with calibration_target_estimates range.

        Catches scale mismatches like ratio (0-1) vs score (0-3) before calibration.

        Requires context:
            species_units: Dict mapping species names to unit strings (from species_units.json)
        """
        # Skip for IsolatedSystemTarget (uses submodel.observable instead)
        if type(self).__name__ == "IsolatedSystemTarget":
            return self

        from qsp_llm_workflows.core.unit_registry import ureg

        # Get species_units from context
        if not info.context:
            raise ValueError(
                "Validation context is required. Pass context={'species_units': {...}}"
            )
        species_units = info.context["species_units"]

        # Get calibration target range
        # For vector data, use overall statistics across all index points
        estimates = self.calibration_target_estimates

        # Flatten ci95 to get overall min/max
        all_ci_values: list[float] = []
        for ci_pair in estimates.ci95:
            all_ci_values.extend(ci_pair)
        target_min = float(min(all_ci_values))
        target_max = float(max(all_ci_values))

        # Use median of medians for representative central value
        target_median = float(np.median(estimates.median))

        try:
            # Create mock time array
            n_timepoints = 50
            mock_time = np.linspace(0, 100, n_timepoints) * ureg.day

            # Create mock species with INDEPENDENT variation
            # Key improvement: vary species with different phases so ratios actually vary
            mock_species = {}
            for idx, species_name in enumerate(self.observable.species):
                # Get unit from species_units (handle both dict and string formats)
                species_info = species_units.get(species_name, "cell")
                if isinstance(species_info, dict):
                    unit_str = species_info.get("units", "cell")
                else:
                    unit_str = species_info

                # Use biologically realistic base values based on unit type
                base_value = get_typical_species_value(unit_str)

                # Vary each species with a different phase offset
                # This ensures ratios will vary, exposing conversion factor issues
                phase_offset = idx * np.pi / max(len(self.observable.species), 1)
                variation = 1 + 0.8 * np.sin(np.linspace(0, 4 * np.pi, n_timepoints) + phase_offset)

                # Also include some magnitude variation (±1 order of magnitude)
                magnitude_variation = np.logspace(-0.5, 0.5, n_timepoints)

                values = base_value * variation * magnitude_variation
                mock_species[species_name] = values * ureg(unit_str)

            # Execute observable.code
            local_scope = {"ureg": ureg, "np": np}
            exec(self.observable.code, local_scope)
            compute_fn = local_scope["compute_observable"]

            # Build constants dict from observable.constants
            constants = {}
            for const in self.observable.constants:
                constants[const.name] = const.value * ureg(const.units)

            result = compute_fn(mock_time, mock_species, constants, ureg)

            # Get code output statistics
            result_magnitude = np.atleast_1d(result.magnitude)
            code_min = float(np.min(result_magnitude))
            code_max = float(np.max(result_magnitude))
            code_median = float(np.median(result_magnitude))
            code_std = float(np.std(result_magnitude))

            # Check for scale mismatch patterns
            # Pattern 1: Code outputs ratio (0-1) but target is score (>2)
            if code_max <= 1.5 and target_max > 2.0:
                raise ScaleMismatchError(
                    f"Scale mismatch detected - likely ratio (0-1) vs score (0-N) mismatch:\n"
                    f"  • Calibration target: median={target_median:.3g}, range=[{target_min:.3g}, {target_max:.3g}]\n"
                    f"  • Observable code:    median={code_median:.3g}, range=[{code_min:.3g}, {code_max:.3g}]\n"
                    f"The observable.code outputs values on 0-1 scale (likely a ratio/fraction),\n"
                    f"but calibration target is on a larger scale (likely a 0-N score).\n"
                    f"Fix: Either scale the calibration target down to 0-1, or scale the observable.code up to 0-N."
                )

            # Pattern 2: Code outputs score (>2) but target is ratio (0-1)
            if code_max > 2.0 and target_max <= 1.5:
                raise ScaleMismatchError(
                    f"Scale mismatch detected - likely score (0-N) vs ratio (0-1) mismatch:\n"
                    f"  • Calibration target: median={target_median:.3g}, range=[{target_min:.3g}, {target_max:.3g}]\n"
                    f"  • Observable code:    median={code_median:.3g}, range=[{code_min:.3g}, {code_max:.3g}]\n"
                    f"The observable.code outputs values on 0-N scale (likely a score),\n"
                    f"but calibration target is on 0-1 scale (likely a ratio/fraction).\n"
                    f"Fix: Either scale the calibration target up to 0-N, or scale the observable.code down to 0-1."
                )

            # Pattern 3: Ranges don't overlap and differ by >10x
            tolerance = 10.0
            if code_median > 0 and target_median > 0:
                median_ratio = max(target_median, code_median) / min(target_median, code_median)

                # Check if ranges don't overlap
                ranges_overlap = not (code_max < target_min or code_min > target_max)

                if not ranges_overlap and median_ratio > tolerance:
                    raise ScaleMismatchError(
                        f"Scale mismatch detected - output scale differs by {median_ratio:.1f}x:\n"
                        f"  • Calibration target: median={target_median:.3g}, range=[{target_min:.3g}, {target_max:.3g}]\n"
                        f"  • Observable code:    median={code_median:.3g}, range=[{code_min:.3g}, {code_max:.3g}]\n"
                        f"The observable.code output is on a different scale than the calibration target.\n"
                        f"Check for missing unit conversions or scaling factors."
                    )

            # Pattern 4: Absolute magnitude check
            # Even if ranges "overlap" due to mock data spread, flag if
            # medians are wildly different (>100×)
            if code_median > 0 and target_median > 0:
                absolute_ratio = max(target_median, code_median) / min(target_median, code_median)
                if absolute_ratio > 100:
                    raise ScaleMismatchError(
                        f"Magnitude mismatch detected - medians differ by {absolute_ratio:.0f}×:\n"
                        f"  • Calibration target median: {target_median:.3g}\n"
                        f"  • Observable code median:    {code_median:.3g}\n"
                        f"The observable.code output magnitude is very different from the calibration target.\n"
                        f"This often indicates a wrong conversion factor (e.g., 1e-8 instead of 2.27e-4).\n"
                        f"Check: area_per_cell calculations, volume conversions, or density scaling factors."
                    )

            # Pattern 5: Variability check
            # If inputs vary but output is constant, formula may be wrong
            if code_median != 0:
                code_cv = code_std / abs(code_median)
                if code_cv < 1e-6:
                    # Output is effectively constant despite varying inputs
                    import warnings

                    warnings.warn(
                        f"Observable code output is constant (CV={code_cv:.2e}) despite varying inputs.\n"
                        f"This may indicate the formula doesn't use all declared species correctly,\n"
                        f"or contains hardcoded values that override the species inputs.",
                        UserWarning,
                    )

        except CalibrationTargetValidationError:
            # Re-raise all our custom validation errors
            raise
        except Exception:
            # Other errors (e.g., complex mock data requirements) - be lenient
            # The observable.code might use logic we can't easily mock
            pass

        return self

    @model_validator(mode="after")
    def validate_species_completeness(self) -> "CalibrationTarget":
        """
        Validator (WARNING): Check for potentially missing related species.

        When measuring "total" quantities (e.g., total CD8 via pan-CD8 antibody),
        warns if related species that should be summed are not included.
        """
        # Skip for IsolatedSystemTarget (uses submodel.observable instead)
        if type(self).__name__ == "IsolatedSystemTarget":
            return self

        import warnings

        # Related species pairs - if one is used for a "total" measurement,
        # the other should likely be included too
        RELATED_SPECIES = {
            "V_T.CD8": ["V_T.CD8_exh"],
            "V_T.CD8_exh": ["V_T.CD8"],
            "V_T.Th": ["V_T.Treg"],
            "V_T.Treg": ["V_T.Th"],
            "V_T.M1": ["V_T.M2"],
            "V_T.M2": ["V_T.M1"],
        }

        # Keywords suggesting a "total" measurement
        TOTAL_KEYWORDS = ["total", "all", "overall", "pan-", "combined"]

        rationale_lower = self.rationale.lower()
        uses_total = any(kw in rationale_lower for kw in TOTAL_KEYWORDS)

        if not uses_total:
            return self

        used_species = set(self.observable.species)
        for species in self.observable.species:
            related = RELATED_SPECIES.get(species, [])
            missing = [r for r in related if r not in used_species]
            if missing:
                warnings.warn(
                    f"Species completeness: '{species}' used for 'total' measurement "
                    f"but related species {missing} not included.\n"
                    f"If measuring total CD8+ via pan-CD8 antibody, include both CD8 and CD8_exh.",
                    UserWarning,
                )

        return self

    @model_validator(mode="after")
    def validate_no_control_characters(self) -> "CalibrationTarget":
        """
        Validator: Check for control characters in all string fields.

        Control characters (especially in titles, descriptions, snippets) can cause
        YAML parsing failures and other issues. This validator detects them early.

        Checks for:
        - ASCII control characters (0x00-0x1F) except tab (0x09), LF (0x0A), CR (0x0D)
        - DEL character (0x7F)
        - Unicode control characters (U+0080-U+009F)
        """
        import re

        # Pattern to match control characters (excluding valid whitespace)
        # \x00-\x08: NUL through BACKSPACE
        # \x0B-\x0C: VERTICAL TAB, FORM FEED
        # \x0E-\x1F: SHIFT OUT through UNIT SEPARATOR
        # \x7F: DEL
        # \x80-\x9F: Unicode control characters
        control_char_pattern = re.compile(r"[\x00-\x08\x0B-\x0C\x0E-\x1F\x7F\x80-\x9F]")

        def check_string(value: str, field_path: str) -> None:
            """Check a string for control characters."""
            match = control_char_pattern.search(value)
            if match:
                char_code = ord(match.group(0))
                char_hex = f"0x{char_code:02X}"
                # Get position in string
                pos = match.start()
                # Get context around the control character
                context_start = max(0, pos - 20)
                context_end = min(len(value), pos + 20)
                context = value[context_start:context_end]
                # Replace control char with placeholder for display
                context_display = context.replace(match.group(0), f"[{char_hex}]")

                raise ControlCharacterError(
                    f"Control character {char_hex} found in field '{field_path}' at position {pos}.\n"
                    f"Context: ...{context_display}...\n"
                    f"Control characters cause YAML parsing failures and must be removed.\n"
                    f"Common causes: copying from PDFs, word processors, or web pages with special formatting.\n"
                    f"Fix: Re-type the text or use a plain text editor to remove invisible characters."
                )

        def walk_and_check(obj, path: str = "") -> None:
            """Recursively walk through the object and check all strings."""
            if isinstance(obj, str):
                check_string(obj, path)
            elif isinstance(obj, dict):
                for key, value in obj.items():
                    walk_and_check(value, f"{path}.{key}" if path else key)
            elif isinstance(obj, list):
                for i, item in enumerate(obj):
                    walk_and_check(item, f"{path}[{i}]")
            elif hasattr(obj, "model_dump"):
                # Pydantic model - convert to dict and recurse
                walk_and_check(obj.model_dump(), path)

        # Check all fields in the model
        walk_and_check(self.model_dump(), "CalibrationTarget")

        return self
