#!/usr/bin/env python3
"""
Pydantic models for Calibration Targets.

Calibration targets are raw observables extracted from literature, used to calibrate
QSP model parameters via Bayesian inference. Each observable has an experimental
context that may differ from the model context, requiring formal mismatch handling.

See docs/calibration_target_design.md for full specification.
"""

import ast
from enum import Enum
from typing import List, Optional, Union

import numpy as np
from pydantic import BaseModel, Field, ValidationInfo, field_validator, model_validator

# Import from calibration submodules
from qsp_llm_workflows.core.calibration.enums import (
    IndicationMatch,
    PerturbationType,
    SourceQuality,
    SourceType,
    TMECompatibility,
)
from qsp_llm_workflows.core.calibration.exceptions import (
    ArrayLengthError,
    CalibrationTargetValidationError,
    CodeStructureError,
    CodeSyntaxError,
    ComputedValueMismatchError,
    ControlCharacterError,
    DimensionalityMismatchError,
    DOIResolutionError,
    HardcodedConstantError,
    MissingUnitsError,
    PaperTitleMismatchError,
    ReturnStructureError,
    ScaleMismatchError,
    ScalarReturnError,
    SnippetValueMismatchError,
    SourceRefError,
    SpeciesNotFoundError,
    UnitConversionError,
    UnitParsingError,
)
from qsp_llm_workflows.core.calibration.experimental_context import ExperimentalContext
from qsp_llm_workflows.core.calibration.observable import (
    AggregationType,
    ConstantSourceType,
    Observable,
)
from qsp_llm_workflows.core.calibration.scenario import Scenario
from qsp_llm_workflows.core.calibration.shared_models import (
    EstimateInput,
    ModelingAssumption,
    SecondarySource,
    Source,
    SourceRelevanceAssessment,
)
from qsp_llm_workflows.core.calibration.validators import (
    check_value_in_text,
    create_mock_species,
    fuzzy_match,
    resolve_doi,
)


# ============================================================================
# Calibration Target
# ============================================================================


class CalibrationTargetFooters(BaseModel):
    """
    Footer fields for calibration target files.

    These are metadata about the file itself (not generated by LLM):
    - What observable is being tracked
    - Which cancer type
    - When and how it was derived
    """

    calibration_target_id: str = Field(description="Unique calibration target identifier")
    cancer_type: str = Field(description="Cancer type (e.g., 'PDAC')")
    tags: List[str] = Field(default_factory=list, description="Metadata tags")
    derivation_id: Optional[str] = Field(None, description="Unique derivation identifier")
    derivation_timestamp: Optional[str] = Field(None, description="ISO timestamp of derivation")


class IndexType(str, Enum):
    """Type of index dimension for vector-valued calibration targets."""

    TIME = "time"  # Time-course data (e.g., measurements at Day 0, 7, 14)
    DOSE = "dose"  # Dose-response data (e.g., drug concentrations)
    RATIO = "ratio"  # Ratio-based index (e.g., E:T ratios)
    CONCENTRATION = "concentration"  # Concentration series
    OTHER = "other"  # Other index types


class CalibrationTargetEstimates(BaseModel):
    """
    Calibration target estimates with structured inputs and derivation.

    Supports both scalar and vector-valued outputs:
    - Scalar: Single measurement → length-1 lists (median=[42.0], ci95=[[37.0, 47.0]])
    - Vector: Multi-point data → lists matching index_values length

    Vector-valued outputs are indexed by index_values (e.g., time points, doses).
    """

    median: List[float] = Field(
        description=(
            "COMPUTED median value(s) from distribution_code. "
            "Length-1 list for scalar data, or list matching index_values length for vector data."
        )
    )
    ci95: List[List[float]] = Field(
        description=(
            "COMPUTED 95% confidence intervals from distribution_code. "
            "List of [lower, upper] pairs. Length-1 for scalar data ([[lo, hi]]), "
            "or matching index_values length for vector data."
        )
    )
    units: str = Field(description="Units of the observable (Pint-parseable)")

    # Sample size metadata
    sample_size: Union[int, List[int]] = Field(
        description=(
            "Sample size (n) for the measurement. CRITICAL for uncertainty quantification "
            "and pooling across studies.\n\n"
            "WHERE TO LOOK:\n"
            "- 'n = X' or 'N = X' in methods/results sections\n"
            "- Sample sizes in figure legends (e.g., 'n=5 per group')\n"
            "- Patient/subject counts in study design\n"
            "- Number of replicates in in vitro experiments\n"
            "- Number of animals per group in preclinical studies\n\n"
            "FORMAT:\n"
            "- Single int for scalar data or same n for all index points\n"
            "- List[int] for different sample sizes at each index point\n\n"
            "IF NOT REPORTED:\n"
            "- Check figure error bars - if SEM is reported, can back-calculate n from SD/SEM\n"
            "- Use conservative estimate based on study type\n"
            "- Document uncertainty in sample_size_rationale"
        )
    )
    sample_size_rationale: str = Field(
        description=(
            "Explanation of how sample_size was determined.\n\n"
            "Examples:\n"
            "- 'n=5 per group stated in Methods section 2.3'\n"
            "- 'n inferred from figure error bars using SEM formula: n = (SD/SEM)²'\n"
            "- 'n estimated as typical for this study type; not explicitly reported'\n"
            "- 'n=3 replicates per condition, standard for in vitro T cell assays'"
        )
    )

    # Index dimension for vector-valued data
    index_values: Optional[List[float]] = Field(
        None,
        description=(
            "Index values for vector-valued data (e.g., [0, 24, 48, 72] for time points). "
            "None for scalar data. Vector-valued inputs and outputs must match this length."
        ),
    )
    index_unit: Optional[str] = Field(
        None,
        description="Units for index_values (e.g., 'hour', 'day', 'nanomolar'). Required if index_values provided.",
    )
    index_type: Optional[IndexType] = Field(
        None,
        description="Type of index dimension. Required if index_values provided.",
    )

    inputs: List[EstimateInput] = Field(
        description=(
            "List of literature-extracted inputs used in distribution_code derivation. "
            "These are the VALUES REPORTED IN THE PAPER (mean, SD, median, IQR, trajectories, etc.) "
            "that are used to DERIVE the distribution via Monte Carlo. "
            "Inputs can be scalar (broadcast to all index points) or vector-valued (same length as index_values).\n\n"
            "NOTE: For inputs used in submodel or observable code, use submodel.inputs or observable.inputs instead."
        )
    )
    assumptions: List[ModelingAssumption] = Field(
        default_factory=list,
        description=(
            "List of modeling assumptions used in derivation. "
            "These are values NOT from the paper but needed for computation (e.g., n_mc_samples, "
            "assumed_cv when not reported). Each must have a rationale field explaining the choice."
        ),
    )
    distribution_code: str = Field(
        description=(
            "Python code defining a derive_distribution(inputs, ureg) function.\n"
            "inputs is a dict mapping input names to Pint Quantities (scalar or array).\n"
            "Must return dict with Pint Quantities:\n"
            "  - median_obs: median value(s) as Pint Quantity\n"
            "  - ci95_lower: lower CI bound(s) as Pint Quantity\n"
            "  - ci95_upper: upper CI bound(s) as Pint Quantity\n\n"
            "For scalar data, return scalar Quantities.\n"
            "For vector data, return array Quantities matching index_values length.\n\n"
            "GOLDEN RULE: Reattach units immediately after sampling, then they propagate.\n"
            "np.median, np.percentile, np.mean, np.std all preserve Pint units.\n\n"
            "Example (scalar - single measurement):\n"
            "def derive_distribution(inputs, ureg):\n"
            "    import numpy as np\n"
            "    rng = np.random.default_rng(42)\n"
            "    mean = inputs['cd8_density_mean']\n"
            "    sd = inputs['cd8_density_sd']\n"
            "    # Reattach units immediately after sampling\n"
            "    samples = rng.normal(mean.magnitude, sd.magnitude, 10000) * mean.units\n"
            "    # np.median and np.percentile preserve units\n"
            "    return {\n"
            "        'median_obs': np.median(samples),\n"
            "        'ci95_lower': np.percentile(samples, 2.5),\n"
            "        'ci95_upper': np.percentile(samples, 97.5),\n"
            "    }\n\n"
            "Example (vector - time-course data):\n"
            "def derive_distribution(inputs, ureg):\n"
            "    import numpy as np\n"
            "    rng = np.random.default_rng(42)\n"
            "    means = inputs['cd8_density_mean']  # Quantity array\n"
            "    sds = inputs['cd8_density_sd']  # Quantity array\n"
            "    n_points = len(means.magnitude)\n"
            "    medians, lowers, uppers = [], [], []\n"
            "    for i in range(n_points):\n"
            "        # Reattach units immediately\n"
            "        samples = rng.normal(means.magnitude[i], sds.magnitude[i], 10000) * means.units\n"
            "        medians.append(np.median(samples).magnitude)\n"
            "        lowers.append(np.percentile(samples, 2.5).magnitude)\n"
            "        uppers.append(np.percentile(samples, 97.5).magnitude)\n"
            "    return {\n"
            "        'median_obs': np.array(medians) * means.units,\n"
            "        'ci95_lower': np.array(lowers) * means.units,\n"
            "        'ci95_upper': np.array(uppers) * means.units,\n"
            "    }"
        )
    )

    @field_validator("sample_size")
    @classmethod
    def validate_sample_size_positive(cls, v: Union[int, List[int]]) -> Union[int, List[int]]:
        """Validate sample size is at least 1."""
        if isinstance(v, list):
            for i, n in enumerate(v):
                if n < 1:
                    raise ValueError(f"sample_size[{i}] must be at least 1, got {n}")
        else:
            if v < 1:
                raise ValueError(f"sample_size must be at least 1, got {v}")
        return v

    @model_validator(mode="after")
    def validate_output_lengths_match(self) -> "CalibrationTargetEstimates":
        """Validator: Ensure median and ci95 have the same length."""
        n_median = len(self.median)
        n_ci95 = len(self.ci95)

        if n_median != n_ci95:
            raise ValueError(
                f"Output array lengths must match: median has {n_median}, ci95 has {n_ci95}"
            )

        # Check ci95 inner structure
        for i, ci in enumerate(self.ci95):
            if len(ci) != 2:
                raise ValueError(f"ci95[{i}] must be [lower, upper] pair, got {len(ci)} elements")

        return self

    @model_validator(mode="after")
    def validate_index_fields_consistent(self) -> "CalibrationTargetEstimates":
        """Validator: Ensure index_* fields are all present or all absent."""
        has_values = self.index_values is not None
        has_unit = self.index_unit is not None
        has_type = self.index_type is not None

        if has_values:
            if not has_unit:
                raise ValueError("index_unit is required when index_values is provided")
            if not has_type:
                raise ValueError("index_type is required when index_values is provided")

            # Check that output length matches index_values length
            # Type narrowing: we know index_values is not None here
            assert self.index_values is not None  # for type checker
            n_index = len(self.index_values)
            n_output = len(self.median)
            if n_output != n_index:
                raise ValueError(
                    f"Output length ({n_output}) must match index_values length ({n_index})"
                )
        else:
            # Scalar case: must have length 1
            if len(self.median) != 1:
                raise ValueError(
                    f"For scalar data (no index_values), outputs must have length 1, "
                    f"got {len(self.median)}"
                )

        return self

    @model_validator(mode="after")
    def validate_vector_input_lengths(self) -> "CalibrationTargetEstimates":
        """Validator: Ensure vector-valued inputs and assumptions match index_values length."""
        if self.index_values is None:
            return self  # Scalar case, skip

        n_index = len(self.index_values)

        # Check literature inputs
        for inp in self.inputs:
            if isinstance(inp.value, list):
                if len(inp.value) != n_index:
                    raise ValueError(
                        f"Vector input '{inp.name}' has length {len(inp.value)}, "
                        f"but index_values has length {n_index}. "
                        f"Vector inputs must match index_values length."
                    )

        # Check assumptions
        for assumption in self.assumptions:
            if isinstance(assumption.value, list):
                if len(assumption.value) != n_index:
                    raise ValueError(
                        f"Vector assumption '{assumption.name}' has length {len(assumption.value)}, "
                        f"but index_values has length {n_index}. "
                        f"Vector assumptions must match index_values length."
                    )

        return self

    @model_validator(mode="after")
    def validate_sample_size_length(self) -> "CalibrationTargetEstimates":
        """Validator: Ensure vector sample_size matches index_values length."""
        if isinstance(self.sample_size, list):
            if self.index_values is None:
                raise ValueError(
                    "Vector sample_size requires index_values. " "Use a single int for scalar data."
                )
            if len(self.sample_size) != len(self.index_values):
                raise ValueError(
                    f"sample_size length ({len(self.sample_size)}) must match "
                    f"index_values length ({len(self.index_values)})"
                )
        return self


class CalibrationTarget(BaseModel):
    """
    A calibration target: a raw observable extracted from literature.

    Used to calibrate QSP model parameters via Bayesian inference.

    Excludes header fields that are added during unpacking:
    - calibration_target_id, cancer_type
    - tags, derivation_id, derivation_timestamp
    """

    # --- Observable fields (LLM-generated) ---
    empirical_data: CalibrationTargetEstimates = Field(
        description="Observable estimates with inputs and derivation"
    )

    # ========================================================================
    # Field definitions
    # ========================================================================

    # --- Observable specification (LLM-generated) ---
    observable: Observable = Field(
        description=(
            "How to compute the experimental observable from full model species. "
            "Defines the code that transforms model output to match literature measurements."
        )
    )

    # --- Experimental context (LLM-generated, grouped for distance calculations) ---
    experimental_context: ExperimentalContext = Field(
        description="Experimental context of the observable"
    )

    # --- Scenario (optional, for intervention tracking) ---
    scenario: Optional[Scenario] = Field(
        default=None,
        description=(
            "Experimental scenario with interventions. Optional - can be omitted if "
            "no interventions or if intervention details are captured in study_interpretation."
        ),
    )

    # --- Narrative and assumptions (LLM-generated) ---
    study_interpretation: str = Field(
        description=(
            "Overall interpretation of the study and how it relates to the model.\n"
            "Explain what observable is being measured, how the experimental context maps "
            "to the model, and any key methodological considerations.\n"
            "Keep focused on the scientific interpretation, not assumptions or limitations."
        )
    )

    key_assumptions: List[str] = Field(
        min_length=1,
        description=(
            "List of key assumptions made in extracting or interpreting this calibration target.\n"
            "Include both biological assumptions (e.g., cell type equivalence) and "
            "statistical/methodological assumptions (e.g., normal distribution assumed).\n"
            "Examples:\n"
            "- 'CD8+ T cells measured include both effector and exhausted phenotypes'\n"
            "- 'Normal distribution assumed for positive-only data (may introduce bias)'\n"
            "- 'Mouse data assumed transferable to human with 5-10x rate reduction'"
        ),
    )

    key_study_limitations: List[str] = Field(
        default_factory=list,
        description=(
            "List of study limitations that affect the calibration target validity.\n"
            "Focus on issues that could bias the estimates or limit generalizability.\n"
            "Examples:\n"
            "- 'Single-center cohort (n~15), limited generalizability'\n"
            "- 'Values estimated from figures, not tabulated data'\n"
            "- 'Bulk CD3+ assay, not CD8-specific'"
        ),
    )

    # --- Sources (LLM-generated) ---
    primary_data_source: Source = Field(
        description="Primary data source (the paper where this observable was measured)"
    )
    secondary_data_sources: List[SecondarySource] = Field(
        default_factory=list, description="Secondary data sources (reference values, constants)"
    )

    # --- Source relevance (optional for CalibrationTarget, required for SubmodelTarget) ---
    source_relevance: Optional[SourceRelevanceAssessment] = Field(
        default=None,
        description=(
            "Structured assessment of how well the source data translates to the target model. "
            "Optional for CalibrationTarget (typically exact-match human clinical data). "
            "Captures indication match, source quality, perturbation context, and TME compatibility."
        ),
    )

    @classmethod
    def get_header_fields(cls) -> set[str]:
        """Get set of field names that are headers (from CalibrationTargetFooters)."""
        return set(CalibrationTargetFooters.model_fields.keys())

    def split(self) -> tuple[CalibrationTargetFooters, dict]:
        """
        Split into headers and content.

        Returns:
            Tuple of (headers_model, content_dict)
        """
        header_fields = self.get_header_fields()
        all_data = self.model_dump()

        # Extract headers
        header_data = {k: v for k, v in all_data.items() if k in header_fields}
        headers = CalibrationTargetFooters(**header_data)

        # Extract content
        content = {k: v for k, v in all_data.items() if k not in header_fields}

        return headers, content

    @classmethod
    def from_split(cls, headers: CalibrationTargetFooters, content: dict) -> "CalibrationTarget":
        """
        Create CalibrationTarget from headers and content.

        Args:
            headers: CalibrationTargetFooters instance
            content: Content dictionary (LLM-generated fields)

        Returns:
            Complete CalibrationTarget instance
        """
        return cls(**{**headers.model_dump(), **content})

    @model_validator(mode="after")
    def validate_doi_resolution(self) -> "CalibrationTarget":
        """Validator: Check that primary DOI resolves via CrossRef."""
        if self.primary_data_source.doi:
            metadata = resolve_doi(self.primary_data_source.doi)
            if metadata is None:
                raise DOIResolutionError(
                    f"DOI '{self.primary_data_source.doi}' failed to resolve via CrossRef.\n\n"
                    "Possible causes:\n"
                    "  1. DOI is incorrect or has typos\n"
                    "  2. DOI format is wrong (should be like '10.1234/journal.2023.123')\n"
                    "  3. CrossRef API is temporarily unavailable\n"
                    "  4. Paper is too new and not yet indexed\n\n"
                    "How to fix:\n"
                    "  - Search for the paper on Google Scholar or PubMed\n"
                    "  - Click 'Cite' or look for the DOI on the publisher's page\n"
                    "  - Verify the DOI resolves at https://doi.org/<your-doi>"
                )
        return self

    @model_validator(mode="after")
    def validate_title_match(self) -> "CalibrationTarget":
        """Validator: Check that paper title matches CrossRef metadata."""
        if self.primary_data_source.doi:
            metadata = resolve_doi(self.primary_data_source.doi)
            if metadata:
                crossref_title = metadata.get("title", "")
                # Handle case where CrossRef returns empty or list title
                if not crossref_title or crossref_title == "[]":
                    # CrossRef has no title - skip validation but warn
                    return self
                if not fuzzy_match(crossref_title, self.primary_data_source.title, threshold=0.75):
                    raise PaperTitleMismatchError(
                        f"Paper title mismatch:\n"
                        f"  CrossRef: '{crossref_title}'\n"
                        f"  Provided: '{self.primary_data_source.title}'\n\n"
                        f"How to fix:\n"
                        f"  - Copy the exact title from the paper or publisher's website\n"
                        f"  - Check for special characters, subscripts, or abbreviations\n"
                        f"  - Ensure the DOI matches the paper you're citing"
                    )
        return self

    @model_validator(mode="after")
    def validate_secondary_doi_resolution(self) -> "CalibrationTarget":
        """Validator: Check that secondary source DOIs resolve via CrossRef.

        Secondary sources use doi_or_url field which can be a DOI or URL.
        Only validates entries that look like DOIs (start with '10.').
        """
        for source in self.secondary_data_sources:
            doi_or_url = source.doi_or_url
            if not doi_or_url:
                continue

            # Check if it looks like a DOI (starts with 10. or contains doi.org)
            is_doi = doi_or_url.startswith("10.") or "doi.org/10." in doi_or_url

            if is_doi:
                metadata = resolve_doi(doi_or_url)
                if metadata is None:
                    raise DOIResolutionError(
                        f"Secondary source '{source.source_tag}' has DOI '{doi_or_url}' "
                        f"that failed to resolve via CrossRef.\n\n"
                        f"Possible causes:\n"
                        f"  1. DOI is incorrect or has typos\n"
                        f"  2. CrossRef API is temporarily unavailable\n"
                        f"  3. This is actually a URL, not a DOI\n\n"
                        f"How to fix:\n"
                        f"  - Verify the DOI at https://doi.org/{doi_or_url}\n"
                        f"  - If this is a URL (not DOI), use a different format that doesn't start with '10.'"
                    )
        return self

    @model_validator(mode="after")
    def validate_secondary_title_match(self) -> "CalibrationTarget":
        """Validator: Check that secondary source titles match CrossRef metadata.

        Only validates entries with DOIs (not URLs).
        """
        for source in self.secondary_data_sources:
            doi_or_url = source.doi_or_url
            if not doi_or_url:
                continue

            # Check if it looks like a DOI
            is_doi = doi_or_url.startswith("10.") or "doi.org/10." in doi_or_url

            if is_doi:
                metadata = resolve_doi(doi_or_url)
                if metadata:
                    crossref_title = metadata.get("title", "")
                    # Handle case where CrossRef returns empty or list title
                    if not crossref_title or crossref_title == "[]":
                        # CrossRef has no title - skip validation
                        continue
                    if not fuzzy_match(crossref_title, source.title, threshold=0.75):
                        raise PaperTitleMismatchError(
                            f"Secondary source '{source.source_tag}' title mismatch:\n"
                            f"  CrossRef: '{crossref_title}'\n"
                            f"  Provided: '{source.title}'\n\n"
                            f"How to fix:\n"
                            f"  - Copy the exact title from the paper or publisher's website\n"
                            f"  - Check for special characters, subscripts, or abbreviations\n"
                            f"  - Ensure the DOI matches the paper you're citing"
                        )
        return self

    @model_validator(mode="after")
    def validate_units_are_valid_pint(self) -> "CalibrationTarget":
        """
        Validator (ERROR): Statically check that all unit strings are parseable by Pint.

        Catches invalid units early with clear error messages, before they cause
        cryptic Pint failures during code execution.
        """
        # Skip for IsolatedSystemTarget (has its own unit validation)
        if type(self).__name__ == "IsolatedSystemTarget":
            return self

        from qsp_llm_workflows.core.unit_registry import ureg

        errors = []

        def _check_unit(unit_str: Optional[str], location: str) -> None:
            if unit_str is None:
                return
            try:
                ureg(unit_str)
            except Exception as e:
                errors.append(f"{location}: '{unit_str}' ({e})")

        # observable.units
        _check_unit(self.observable.units, "observable.units")

        # empirical_data.units
        _check_unit(self.empirical_data.units, "empirical_data.units")

        # observable.constants[*].units
        for const in self.observable.constants:
            _check_unit(const.units, f"observable.constants['{const.name}'].units")

        # observable.inputs[*].units
        for inp in self.observable.inputs:
            _check_unit(inp.units, f"observable.inputs['{inp.name}'].units")

        # empirical_data.index_unit
        _check_unit(self.empirical_data.index_unit, "empirical_data.index_unit")

        # aggregation.time_unit (if present)
        if (
            self.observable.aggregation is not None
            and self.observable.aggregation.time_unit is not None
        ):
            _check_unit(self.observable.aggregation.time_unit, "observable.aggregation.time_unit")

        if errors:
            raise UnitParsingError.from_errors(errors)

        return self

    @model_validator(mode="after")
    def validate_observable_code_units(self, info: ValidationInfo) -> "CalibrationTarget":
        """
        Validator: Check that observable code executes and returns correct units.

        Requires context:
            species_units: Dict mapping species names to unit strings (from species_units.json)
        """
        # Skip for IsolatedSystemTarget (uses submodel.observable instead)
        if type(self).__name__ == "IsolatedSystemTarget":
            return self

        from qsp_llm_workflows.core.unit_registry import ureg
        from qsp_llm_workflows.core.calibration.code_validator import (
            CodeType,
            validate_code_block,
        )
        import pint

        # Get species_units from context
        if not info.context:
            raise ValueError(
                "Validation context is required. Pass context={'species_units': {...}}"
            )
        species_units = info.context["species_units"]

        # Use CodeValidator for syntax and signature checks
        result = validate_code_block(
            self.observable.code,
            CodeType.OBSERVABLE,
            check_hardcoded=False,  # Handled by separate validator
            check_execution=False,  # We do custom execution below
        )

        if not result.passed:
            errors = result.get_errors()
            if errors:
                first_error = errors[0]
                if first_error.category == "syntax":
                    raise CodeSyntaxError(
                        f"observable.code has syntax error: {first_error.message}"
                    )
                elif first_error.category == "signature":
                    raise CodeStructureError(first_error.message)
                else:
                    raise CodeStructureError(first_error.message)

        # Execute with mock data
        try:
            # Create mock time array
            mock_time = np.linspace(0, 14, 100) * ureg.day

            # Create mock species from actual model (with matching length)
            mock_species = create_mock_species(species_units, ureg, n_timepoints=len(mock_time))

            # Build constants dict from observable.constants
            constants = {}
            for const in self.observable.constants:
                constants[const.name] = const.value * ureg(const.units)

            # Execute function
            local_scope = {"ureg": ureg, "np": np}
            exec(self.observable.code, local_scope)
            compute_fn = local_scope["compute_observable"]

            result = compute_fn(mock_time, mock_species, constants, ureg)

            # Check result has units
            if not hasattr(result, "units"):
                raise MissingUnitsError("Function must return a Pint Quantity with units")

            # Check dimensionality matches calibration target units
            expected_quantity = 1.0 * ureg(self.empirical_data.units)
            if result.dimensionality != expected_quantity.dimensionality:
                raise DimensionalityMismatchError(
                    f"Observable code unit dimensionality mismatch:\n"
                    f"  Expected: {self.empirical_data.units} ({expected_quantity.dimensionality})\n"
                    f"  Got: {result.units} ({result.dimensionality})"
                )

            # Check result has same length as time series (no time indexing)
            if hasattr(result, "magnitude"):
                result_magnitude = result.magnitude
                # Handle both scalar and array results
                if np.isscalar(result_magnitude):
                    raise ScalarReturnError(
                        f"Observable code returned a scalar, but should return an array with same length as time series.\n"
                        f"  Expected length: {len(mock_time)}\n"
                        f"  Got: scalar value\n"
                        f"Do NOT use time indexing (e.g., species[-1] or species[0]) in observable code.\n"
                        f"Compute the observable over the entire time series."
                    )
                elif len(result_magnitude) != len(mock_time):
                    raise ArrayLengthError(
                        f"Observable code returned array with wrong length:\n"
                        f"  Expected: {len(mock_time)} (same as time series)\n"
                        f"  Got: {len(result_magnitude)}\n"
                        f"Do NOT use time indexing. Compute over entire time series."
                    )

        except (
            pint.DimensionalityError,
            pint.UndefinedUnitError,
            pint.OffsetUnitCalculusError,
        ) as e:
            # Wrap Pint unit errors in our custom exception
            raise UnitConversionError(
                f"Observable code has unit error: {str(e)}\n"
                f"Check that all unit operations are dimensionally consistent."
            ) from e
        except CalibrationTargetValidationError:
            # Re-raise all our custom validation errors
            raise
        except Exception:
            # Other errors might be from complex logic or missing species
            # Be lenient - actual execution will catch these
            pass

        return self

    @model_validator(mode="after")
    def validate_aggregation_support_consistency(self) -> "CalibrationTarget":
        """
        Validator (WARNING): Check that population aggregation type is consistent with support.

        Response rates and survival rates produce values in [0, 1], so
        support should be 'unit_interval'.
        """
        # Skip for IsolatedSystemTarget (uses submodel.observable instead)
        if type(self).__name__ == "IsolatedSystemTarget":
            return self

        import warnings

        agg = self.observable.aggregation
        if agg is not None and agg.type in (
            AggregationType.RESPONSE_RATE,
            AggregationType.SURVIVAL_RATE,
        ):
            if self.observable.support != "unit_interval":
                warnings.warn(
                    f"observable.aggregation.type is '{agg.type.value}' which produces values in [0, 1], "
                    f"but observable.support is '{self.observable.support}'. "
                    f"Consider setting support to 'unit_interval'.",
                    UserWarning,
                )

        return self

    @model_validator(mode="after")
    def warn_evaluation_timing(self) -> "CalibrationTarget":
        """
        Validator (WARNING): Warn when time-indexed data has no scenario context.

        Time-course calibration targets need a scenario to anchor the timeline
        (e.g., treatment start, measurement protocol).
        """
        import warnings

        if (
            self.empirical_data.index_type is not None
            and self.empirical_data.index_type == IndexType.TIME
            and self.scenario is None
        ):
            warnings.warn(
                "empirical_data has index_type='time' but no scenario is defined. "
                "Time-course data typically needs a scenario to anchor the timeline "
                "(treatment start, measurement schedule). Consider adding a scenario.",
                UserWarning,
            )

        return self

    @model_validator(mode="after")
    def warn_observation_sd_unreasonable(self) -> "CalibrationTarget":
        """
        Validator (WARNING): Flag unreasonable implied CV from CI95 width.

        Computes implied coefficient of variation from the CI95 width relative
        to the median. Warns if CV > 200% (suspiciously wide) or CV < 1%
        (suspiciously narrow, possibly a copy-paste error).
        """
        import warnings

        for i, (med, ci) in enumerate(zip(self.empirical_data.median, self.empirical_data.ci95)):
            if med == 0:
                continue
            ci_width = ci[1] - ci[0]
            # Approximate SD from CI95 width: SD ≈ CI_width / (2 * 1.96)
            implied_sd = ci_width / 3.92
            implied_cv = abs(implied_sd / med)

            idx_label = f"[{i}]" if len(self.empirical_data.median) > 1 else ""

            if implied_cv > 2.0:
                warnings.warn(
                    f"Implied CV{idx_label} = {implied_cv:.0%} (from CI95 width / median). "
                    f"CV > 200% is unusually large — verify that ci95 and median are in the same units "
                    f"and that the uncertainty hasn't been inflated.",
                    UserWarning,
                )
            elif implied_cv < 0.01:
                warnings.warn(
                    f"Implied CV{idx_label} = {implied_cv:.2%} (from CI95 width / median). "
                    f"CV < 1% is unusually small — verify that ci95 bounds differ from the median "
                    f"and aren't copy-paste duplicates.",
                    UserWarning,
                )

        return self

    @model_validator(mode="after")
    def validate_source_quality_peer_reviewed(self) -> "CalibrationTarget":
        """Validator (WARNING): Flag non-peer-reviewed sources."""
        if self.source_relevance is None:
            return self

        import warnings

        if self.source_relevance.source_quality == SourceQuality.NON_PEER_REVIEWED:
            warnings.warn(
                "source_relevance.source_quality is 'non_peer_reviewed'. "
                "Prefer peer-reviewed primary literature for calibration targets. "
                "If this source must be used, document the rationale in key_assumptions.",
                UserWarning,
            )

        return self

    @model_validator(mode="after")
    def validate_cross_indication_uncertainty(self) -> "CalibrationTarget":
        """Validator (WARNING): Flag proxy/unrelated indication with insufficient uncertainty."""
        if self.source_relevance is None:
            return self

        import warnings

        sr = self.source_relevance
        if sr.indication_match in (IndicationMatch.PROXY, IndicationMatch.UNRELATED):
            if sr.estimated_translation_uncertainty_fold < 3.0:
                warnings.warn(
                    f"source_relevance.indication_match is '{sr.indication_match.value}' but "
                    f"estimated_translation_uncertainty_fold is only {sr.estimated_translation_uncertainty_fold}x. "
                    f"Proxy/unrelated indications typically require >= 3x translation uncertainty.",
                    UserWarning,
                )

        return self

    @model_validator(mode="after")
    def validate_pharmacological_perturbation_justification(self) -> "CalibrationTarget":
        """Validator (WARNING): Flag pharmacological perturbation without relevance explanation."""
        if self.source_relevance is None:
            return self

        import warnings

        sr = self.source_relevance
        if sr.perturbation_type == PerturbationType.PHARMACOLOGICAL:
            if not sr.perturbation_relevance:
                warnings.warn(
                    "source_relevance.perturbation_type is 'pharmacological' but "
                    "perturbation_relevance is not provided. Document how the drug-induced "
                    "measurement relates to the physiological parameter being estimated.",
                    UserWarning,
                )

        return self

    @model_validator(mode="after")
    def validate_genetic_perturbation_justification(self) -> "CalibrationTarget":
        """Validator (WARNING): Flag genetic perturbation without relevance explanation."""
        if self.source_relevance is None:
            return self

        import warnings

        sr = self.source_relevance
        if sr.perturbation_type == PerturbationType.GENETIC:
            if not sr.perturbation_relevance:
                warnings.warn(
                    "source_relevance.perturbation_type is 'genetic_perturbation' but "
                    "perturbation_relevance is not provided. Document how the knockout/knockdown "
                    "measurement relates to the wild-type parameter being estimated.",
                    UserWarning,
                )

        return self

    @model_validator(mode="after")
    def validate_low_tme_compatibility_uncertainty(self) -> "CalibrationTarget":
        """Validator (WARNING): Flag low TME compatibility with insufficient uncertainty."""
        if self.source_relevance is None:
            return self

        import warnings

        sr = self.source_relevance
        if sr.tme_compatibility == TMECompatibility.LOW:
            if sr.estimated_translation_uncertainty_fold < 10.0:
                warnings.warn(
                    f"source_relevance.tme_compatibility is 'low' but "
                    f"estimated_translation_uncertainty_fold is only {sr.estimated_translation_uncertainty_fold}x. "
                    f"Low TME compatibility typically requires >= 10x translation uncertainty.",
                    UserWarning,
                )
            if not sr.tme_compatibility_notes:
                warnings.warn(
                    "source_relevance.tme_compatibility is 'low' but tme_compatibility_notes "
                    "is not provided. Document the TME differences and their expected impact.",
                    UserWarning,
                )

        return self

    @model_validator(mode="after")
    def validate_cross_species_uncertainty(self) -> "CalibrationTarget":
        """Validator (WARNING): Flag cross-species data with insufficient uncertainty."""
        if self.source_relevance is None:
            return self

        import warnings

        sr = self.source_relevance
        if sr.species_source != sr.species_target:
            if sr.estimated_translation_uncertainty_fold < 2.0:
                warnings.warn(
                    f"Cross-species data (source: {sr.species_source}, target: {sr.species_target}) "
                    f"but estimated_translation_uncertainty_fold is only {sr.estimated_translation_uncertainty_fold}x. "
                    f"Cross-species translation typically requires >= 2x uncertainty.",
                    UserWarning,
                )

        return self

    @model_validator(mode="after")
    def validate_input_values_in_snippets(self) -> "CalibrationTarget":
        """Validator: Check that input values appear in their value_snippet.

        Ensures data integrity by verifying that extracted values can be found
        in the source text. Handles multiple numeric formats (decimal, scientific,
        percentage, rounded variations).

        Checks inputs in:
        - empirical_data.inputs (EstimateInput)
        - observable.inputs (SubmodelInput)

        Raises SnippetValueMismatchError if a value is not found in its snippet.
        """

        def check_inputs(inputs, location_prefix: str):
            """Helper to check value_snippet for a list of inputs."""
            from qsp_llm_workflows.core.calibration.shared_models import InputType

            for inp in inputs:
                value = inp.value
                snippet = inp.value_snippet

                if not snippet:
                    continue

                # Skip validation for inferred estimates (values interpreted from qualitative text)
                if hasattr(inp, "input_type") and inp.input_type == InputType.INFERRED_ESTIMATE:
                    continue

                # Skip validation for figure-sourced values (not expected in text snippets)
                if hasattr(inp, "source_type") and inp.source_type == SourceType.FIGURE:
                    continue

                # Handle both scalar and vector-valued inputs
                values_to_check = [value] if not isinstance(value, list) else value

                missing_values = []
                for val in values_to_check:
                    if not check_value_in_text(snippet, val):
                        missing_values.append(val)

                if missing_values:
                    raise SnippetValueMismatchError(
                        f"{location_prefix} input '{inp.name}' has value(s) not found in value_snippet.\n"
                        f"  Missing values: {missing_values}\n"
                        f"  Snippet: '{snippet[:200]}{'...' if len(snippet) > 200 else ''}'\n"
                        f"The value_snippet must contain the exact values extracted from the paper.\n"
                        f"Check for:\n"
                        f"  - Typos in the extracted value\n"
                        f"  - Different numeric format in the paper (e.g., '2.5×10⁻³' vs '0.0025')\n"
                        f"  - Value reported in different units that need conversion\n"
                        f"  - Snippet truncated before the value appears\n"
                        f"  - If value is INTERPRETED from qualitative text, use input_type='inferred_estimate'\n"
                        f"  - If value is READ FROM A FIGURE (plot/chart), use source_type='figure' with figure_id and extraction_method"
                    )

        # Check empirical_data.inputs
        check_inputs(self.empirical_data.inputs, "empirical_data")

        # Check observable.inputs (if present and not IsolatedSystemTarget)
        if type(self).__name__ != "IsolatedSystemTarget" and self.observable.inputs:
            check_inputs(self.observable.inputs, "observable")

        return self

    @model_validator(mode="after")
    def validate_derivation_code(self) -> "CalibrationTarget":
        """
        Validator: Check that derivation_code executes, returns correct structure and units,
        and computed values match reported values (element-wise for vector data).
        """
        from qsp_llm_workflows.core.unit_registry import make_quantity, ureg
        from qsp_llm_workflows.core.calibration.code_validator import (
            CodeType,
            validate_code_block,
        )

        # Use CodeValidator for syntax and signature checks
        result = validate_code_block(
            self.empirical_data.distribution_code,
            CodeType.DISTRIBUTION,
            check_hardcoded=True,  # Check for hardcoded constants with units
            check_execution=False,  # We do custom execution below
        )

        if not result.passed:
            errors = result.get_errors()
            if errors:
                first_error = errors[0]
                if first_error.category == "syntax":
                    raise CodeSyntaxError(
                        f"distribution_code has syntax error: {first_error.message}"
                    )
                elif first_error.category == "signature":
                    raise CodeStructureError(first_error.message)
                elif first_error.category == "hardcoded":
                    # Provide specific guidance for distribution_code
                    raise CodeStructureError(
                        f"{first_error.message}\n\n"
                        "IMPORTANT: distribution_code is for STATISTICAL derivation only.\n"
                        "It converts literature-reported values (mean ± SD) into uncertainty distributions.\n"
                        "It should NOT need model compartment volumes (V_T, V_C, V_P) or physical constants.\n\n"
                        "If you're seeing this error with compartment volumes like 'V_T = 1.0 * ureg.milliliter',\n"
                        "you may be confusing distribution_code with observable.code or submodel.code:\n"
                        "  • distribution_code: Statistical only (mean → samples → median/CI)\n"
                        "  • observable.code: Model simulation (uses compartment volumes, species)\n"
                        "  • submodel.code: ODE dynamics (uses model parameters)\n\n"
                        "If this constant IS needed for statistical derivation, declare it in:\n"
                        "  • empirical_data.inputs (if from literature)\n"
                        "  • empirical_data.assumptions (if a modeling choice)"
                    )
                else:
                    raise CodeStructureError(first_error.message)

        # Execute with mock inputs to test structure and units
        try:
            # Create mock inputs dict with Pint quantities
            # Merge both literature inputs and modeling assumptions into a single dict
            mock_inputs = {}
            # Add literature inputs
            for inp in self.empirical_data.inputs:
                if isinstance(inp.value, list):
                    mock_inputs[inp.name] = np.array(inp.value) * ureg(inp.units)
                else:
                    mock_inputs[inp.name] = make_quantity(inp.value, inp.units)
            # Add modeling assumptions
            for assumption in self.empirical_data.assumptions:
                if isinstance(assumption.value, list):
                    mock_inputs[assumption.name] = np.array(assumption.value) * ureg(
                        assumption.units
                    )
                else:
                    mock_inputs[assumption.name] = assumption.value * ureg(assumption.units)

            # Execute function
            local_scope = {"ureg": ureg, "np": np}
            exec(self.empirical_data.distribution_code, local_scope)
            derive_fn = local_scope["derive_distribution"]

            result = derive_fn(mock_inputs, ureg)

            # Check result is dict with required keys
            if not isinstance(result, dict):
                raise ReturnStructureError("Function must return a dict")

            required_keys = {"median_obs", "ci95_lower", "ci95_upper"}
            if not required_keys.issubset(result.keys()):
                raise ReturnStructureError(
                    f"Function must return dict with keys: {required_keys}. Got: {result.keys()}"
                )

            # Check all returned values have units
            for key in required_keys:
                if not hasattr(result[key], "units"):
                    raise MissingUnitsError(
                        f"Result['{key}'] must be a Pint Quantity with units.\n\n"
                        "The distribution_code returned a plain number without units.\n"
                        "Common cause: Forgot to reattach units after sampling.\n\n"
                        "Fix: Reattach units immediately after sampling.\n\n"
                        "Example:\n"
                        "  samples = rng.normal(mean.magnitude, sd.magnitude, n) * mean.units\n"
                        "  return {\n"
                        "      'median_obs': np.median(samples),\n"
                        "      'ci95_lower': np.percentile(samples, 2.5),\n"
                        "      'ci95_upper': np.percentile(samples, 97.5),\n"
                        "  }"
                    )

            # Check dimensionality matches expected units
            expected_quantity = 1.0 * ureg(self.empirical_data.units)

            for key in required_keys:
                if result[key].dimensionality != expected_quantity.dimensionality:
                    raise DimensionalityMismatchError(
                        f"{key} unit dimensionality mismatch:\n"
                        f"  Expected: {self.empirical_data.units} ({expected_quantity.dimensionality})\n"
                        f"  Got: {result[key].units} ({result[key].dimensionality})"
                    )

            # Convert computed values to expected units for comparison
            median_computed = result["median_obs"].to(self.empirical_data.units)
            ci95_lower_computed = result["ci95_lower"].to(self.empirical_data.units)
            ci95_upper_computed = result["ci95_upper"].to(self.empirical_data.units)

            # Get reported values
            median_reported = self.empirical_data.median
            ci95_reported = self.empirical_data.ci95

            # Tolerances: 1% for median (deterministic), 10% for CI bounds (Monte Carlo variance)
            median_rel_tol = 0.01
            ci95_rel_tol = 0.10

            # Handle array magnitudes (works for both scalar and vector)
            median_mag = np.atleast_1d(median_computed.magnitude)
            ci95_lower_mag = np.atleast_1d(ci95_lower_computed.magnitude)
            ci95_upper_mag = np.atleast_1d(ci95_upper_computed.magnitude)

            # Check lengths match
            n_expected = len(median_reported)
            if len(median_mag) != n_expected:
                raise ReturnStructureError(
                    f"median_obs length mismatch: expected {n_expected}, got {len(median_mag)}"
                )
            if len(ci95_lower_mag) != n_expected:
                raise ReturnStructureError(
                    f"ci95_lower length mismatch: expected {n_expected}, got {len(ci95_lower_mag)}"
                )
            if len(ci95_upper_mag) != n_expected:
                raise ReturnStructureError(
                    f"ci95_upper length mismatch: expected {n_expected}, got {len(ci95_upper_mag)}"
                )

            # Element-wise comparison for median (1% tolerance)
            for i in range(n_expected):
                if abs(median_mag[i] - median_reported[i]) > median_rel_tol * abs(
                    median_reported[i]
                ):
                    raise ComputedValueMismatchError(
                        f"Computed median[{i}] ({median_mag[i]:.4g}) does not match "
                        f"reported median[{i}] ({median_reported[i]:.4g}) within 1% tolerance"
                    )

            # Element-wise comparison for CI95 (10% tolerance for Monte Carlo variance)
            for i in range(n_expected):
                ci_rep = ci95_reported[i]

                if abs(ci95_lower_mag[i] - ci_rep[0]) > ci95_rel_tol * abs(ci_rep[0]):
                    raise ComputedValueMismatchError(
                        f"Computed ci95_lower[{i}] ({ci95_lower_mag[i]:.4g}) does not match "
                        f"reported CI95[{i}] lower ({ci_rep[0]:.4g}) within 10% tolerance"
                    )

                if abs(ci95_upper_mag[i] - ci_rep[1]) > ci95_rel_tol * abs(ci_rep[1]):
                    raise ComputedValueMismatchError(
                        f"Computed ci95_upper[{i}] ({ci95_upper_mag[i]:.4g}) does not match "
                        f"reported CI95[{i}] upper ({ci_rep[1]:.4g}) within 10% tolerance"
                    )

        except CalibrationTargetValidationError:
            # Re-raise all our custom validation errors
            raise
        except Exception as e:
            # Provide helpful guidance for common errors
            error_msg = str(e)
            guidance = ""

            if "setting an array element with a sequence" in error_msg:
                guidance = (
                    "\n\nThis error typically occurs when array structures are inconsistent.\n"
                    "Common cause: Mixing Pint Quantities and plain numbers.\n\n"
                    "Fix: Return flat Pint Quantities for each key.\n\n"
                    "Example:\n"
                    "  samples = rng.normal(mean.magnitude, sd.magnitude, n) * mean.units\n"
                    "  return {\n"
                    "      'median_obs': np.median(samples),\n"
                    "      'ci95_lower': np.percentile(samples, 2.5),\n"
                    "      'ci95_upper': np.percentile(samples, 97.5),\n"
                    "  }"
                )
            elif "unsupported operand type" in error_msg or "cannot convert" in error_msg.lower():
                guidance = (
                    "\n\nThis error often occurs when mixing Pint Quantities with plain numbers.\n"
                    "Ensure all values in calculations have consistent units.\n"
                    "Use inputs['name'].magnitude to extract plain numbers if needed."
                )
            elif "KeyError" in error_msg or "key" in error_msg.lower():
                guidance = (
                    "\n\nThis error suggests a missing input in the inputs dict.\n"
                    "Check that all variables used in distribution_code are defined in:\n"
                    "  - empirical_data.inputs (for literature values)\n"
                    "  - empirical_data.assumptions (for modeling assumptions like n_mc_samples)"
                )

            raise CalibrationTargetValidationError(
                f"Error executing distribution_code: {e}{guidance}"
            ) from e

        return self

    @model_validator(mode="after")
    def validate_source_refs(self) -> "CalibrationTarget":
        """Validator: Check all source_refs in inputs point to defined sources.

        Checks source_refs in:
        - empirical_data.inputs (EstimateInput)
        - observable.inputs (SubmodelInput)
        """
        # Build set of valid source tags from literature sources
        valid_tags = {self.primary_data_source.source_tag}
        valid_tags.update(s.source_tag for s in self.secondary_data_sources)

        def check_refs(inputs, location_prefix: str):
            """Helper to check source_refs for a list of inputs."""
            for inp in inputs:
                if inp.source_ref not in valid_tags:
                    raise SourceRefError(
                        f"{location_prefix} input '{inp.name}' has source_ref '{inp.source_ref}' which is not defined.\n"
                        f"Valid source tags: {sorted(valid_tags)}\n"
                        f"Add the source to primary_data_source or secondary_data_sources.\n"
                        f"For values not from literature, use the 'assumptions' field instead."
                    )

        # Check empirical_data.inputs
        check_refs(self.empirical_data.inputs, "empirical_data")

        # Check observable.inputs (if present and not IsolatedSystemTarget)
        if type(self).__name__ != "IsolatedSystemTarget" and self.observable.inputs:
            check_refs(self.observable.inputs, "observable")

        return self

    @model_validator(mode="after")
    def validate_constant_source_refs(self, info: ValidationInfo) -> "CalibrationTarget":
        """
        Validator (ERROR): Verify observable constant sources are traceable.

        Every observable constant must have a verifiable source:
        - reference_db: reference_db_name must match an entry in reference_values.yaml
        - derived_from_reference_db: all reference_db_names must match entries
        - literature: source_tag must match a defined source in this target

        This prevents ungrounded "modeling assumptions" from entering constants.
        """
        # Skip for IsolatedSystemTarget (uses submodel.observable instead)
        if type(self).__name__ == "IsolatedSystemTarget":
            return self

        if not self.observable.constants:
            return self

        # Build set of valid literature source tags
        valid_tags = {self.primary_data_source.source_tag}
        valid_tags.update(s.source_tag for s in self.secondary_data_sources)

        # Get reference DB names from validation context (if available)
        # reference_db is a dict[str, float] mapping name → value
        reference_db_names = set()
        if info.context and "reference_db" in info.context:
            reference_db_names = set(info.context["reference_db"].keys())

        for const in self.observable.constants:
            if const.source_type == ConstantSourceType.LITERATURE:
                if const.source_tag not in valid_tags:
                    raise SourceRefError(
                        f"Observable constant '{const.name}' has source_tag '{const.source_tag}' "
                        f"which is not defined in this target's sources.\n"
                        f"Valid source tags: {sorted(valid_tags)}\n"
                        f"Add the source to secondary_data_sources, or use "
                        f"source_type='reference_db' with a reference_values.yaml entry."
                    )

            elif const.source_type == ConstantSourceType.REFERENCE_DB:
                if reference_db_names and const.reference_db_name not in reference_db_names:
                    raise SourceRefError(
                        f"Observable constant '{const.name}' references "
                        f"reference_db_name='{const.reference_db_name}' which was not found "
                        f"in reference_values.yaml.\n"
                        f"Available entries: {sorted(reference_db_names)}\n"
                        f"Add the entry to reference_values.yaml or use a different source."
                    )

            elif const.source_type == ConstantSourceType.DERIVED_FROM_REFERENCE_DB:
                if reference_db_names and const.reference_db_names:
                    missing = [
                        name for name in const.reference_db_names if name not in reference_db_names
                    ]
                    if missing:
                        raise SourceRefError(
                            f"Observable constant '{const.name}' derives from reference DB entries "
                            f"that were not found: {missing}\n"
                            f"Available entries: {sorted(reference_db_names)}\n"
                            f"Add the missing entries to reference_values.yaml."
                        )

        return self

    @model_validator(mode="after")
    def validate_species_exist(self, info: ValidationInfo) -> "CalibrationTarget":
        """
        Validator: Check that observable.species exist in model.

        Requires context:
            species_units: Dict mapping species names to unit strings (from species_units.json)
        """
        # Skip for IsolatedSystemTarget (uses submodel.observable instead)
        if type(self).__name__ == "IsolatedSystemTarget":
            return self

        # Get species_units from context
        if not info.context:
            raise ValueError(
                "Validation context is required. Pass context={'species_units': {...}}"
            )
        species_units = info.context["species_units"]
        available_species = set(species_units.keys())

        # Check all observable species exist
        for species in self.observable.species:
            if species not in available_species:
                raise SpeciesNotFoundError(
                    f"observable.species '{species}' not found in model.\n"
                    f"Available species: {sorted(available_species)}\n"
                    f"Check species name format (should be compartment.species, e.g., 'V_T.C1', 'V_T.CD8')"
                )

        return self

    # DISABLED: Simplified measurement structure - executable code deferred to manual implementation
    # @model_validator(mode="after")
    # def validate_threshold_conversion_code(self, info: ValidationInfo) -> "CalibrationTarget":
    #     """Validator disabled for simplified measurement structure."""
    #     return self

    @model_validator(mode="after")
    def validate_clipping_suggests_lognormal(self) -> "CalibrationTarget":
        """
        Validator (WARNING): Check if distribution_code uses clipping.

        Clipping to avoid negative values suggests size/volume data that
        should use lognormal distribution instead of normal.
        """
        import warnings

        code = self.empirical_data.distribution_code

        # Check for clipping patterns
        clipping_patterns = ["np.clip", "np.maximum", "np.minimum", "max(0", "min("]
        if any(pattern in code for pattern in clipping_patterns):
            warnings.warn(
                "distribution_code uses clipping (np.clip/np.maximum/etc) to avoid negative values. "
                "This suggests size/volume/mass data that may be better modeled with a lognormal distribution. "
                "Normal distributions for positive-only data introduce bias when clipped. "
                "Consider converting mean±SD to lognormal parameters: "
                "μ_log = ln(mean²/√(mean²+sd²)), σ_log = √(ln(1+sd²/mean²))",
                UserWarning,
            )

        return self

    @model_validator(mode="after")
    def validate_large_variance_documented(self) -> "CalibrationTarget":
        """
        Validator (WARNING): Check if large variance is documented in limitations.

        CV > 50% suggests substantial variability that should be explained.
        Only applies to scalar inputs (vector inputs are checked per-element elsewhere).
        """
        import warnings

        # Find mean and SD/SE inputs (only scalar inputs)
        mean_input = None
        std_input = None

        for inp in self.empirical_data.inputs:
            # Skip vector-valued inputs for this check
            if isinstance(inp.value, list):
                continue

            name_lower = inp.name.lower()
            if "mean" in name_lower and mean_input is None:
                mean_input = inp
            if any(x in name_lower for x in ["sd", "std", "se", "stderr", "stdev"]):
                std_input = inp

        if mean_input and std_input:
            mean_val = mean_input.value
            std_val = std_input.value

            # Both must be scalar at this point (we skipped lists above)
            if not isinstance(mean_val, list) and not isinstance(std_val, list) and mean_val != 0:
                # Calculate CV (coefficient of variation)
                cv = abs(std_val / mean_val)

                if cv > 0.5:  # CV > 50%
                    # Check if key_study_limitations or study_interpretation mention variance/uncertainty
                    limitations_text = " ".join(self.key_study_limitations).lower()
                    interpretation_lower = self.study_interpretation.lower()
                    combined_text = limitations_text + " " + interpretation_lower
                    variance_keywords = [
                        "variance",
                        "variability",
                        "uncertain",
                        "cv",
                        "wide",
                        "heterogen",
                        "variation",
                        "spread",
                        "dispersion",
                    ]

                    if not any(keyword in combined_text for keyword in variance_keywords):
                        warnings.warn(
                            f"Large coefficient of variation (CV = {cv:.1%}) detected but not discussed in key_study_limitations. "
                            f"Consider adding a limitation explaining whether this reflects biological variability, "
                            f"measurement error, or heterogeneous population.",
                            UserWarning,
                        )

        return self

    @model_validator(mode="after")
    def validate_distribution_choice_for_size_data(self) -> "CalibrationTarget":
        """
        Validator (WARNING): Check if normal distribution used for size data.

        Size/volume/mass measurements are typically lognormal, not normal.
        """
        import warnings

        units = self.empirical_data.units.lower()
        code = self.empirical_data.distribution_code

        # Check if units suggest size/volume/mass
        size_units = ["meter", "liter", "gram", "cell", "mole", "molarity"]
        is_size_data = any(unit in units for unit in size_units) and units != "dimensionless"

        # Check if using normal distribution (but not lognormal)
        uses_normal = ("normal(" in code or "randn" in code) and "lognormal" not in code

        if is_size_data and uses_normal:
            warnings.warn(
                f"Using normal distribution for size/volume/mass data (units: {units}). "
                f"These measurements are typically lognormally distributed. "
                f"Normal distributions can produce non-physical negative values requiring clipping. "
                f"Consider using lognormal distribution instead.",
                UserWarning,
            )

        return self

    @model_validator(mode="after")
    def validate_conversion_factors_documented(self) -> "CalibrationTarget":
        """
        Validator (WARNING): Check that conversion factors are documented.

        Magic numbers in observable.code should be in observable.constants or study_interpretation/key_study_limitations.
        """
        # Skip for IsolatedSystemTarget (uses submodel.observable instead)
        if type(self).__name__ == "IsolatedSystemTarget":
            return self

        import warnings

        # Universal constants to ignore (only truly fundamental values)
        UNIVERSAL_CONSTANTS = {
            # Basic integers
            0,
            1,
            2,
            3,
            4,
            # Mathematical constants
            np.pi,
            3.14159,
            3.141592653589793,
            np.e,
            2.71828,
            2.718281828459045,
            # Common fractions
            0.5,
            0.25,
            0.75,
            # Statistical percentiles (standard)
            2.5,
            25,
            50,
            75,
            97.5,
            0.025,
            0.25,
            0.5,
            0.75,
            0.975,
        }

        code = self.observable.code

        # Extract numeric literals from code
        try:
            tree = ast.parse(code)
            literals = []
            for node in ast.walk(tree):
                if isinstance(node, ast.Constant) and isinstance(node.value, (int, float)):
                    val = node.value
                    # Skip universal constants (with tolerance for floating point)
                    if not any(abs(val - c) < 1e-6 for c in UNIVERSAL_CONSTANTS):
                        literals.append(val)
        except SyntaxError:
            # If code doesn't parse, skip this check
            return self

        if literals:
            # Check if these appear in observable.constants or study_interpretation/key_study_limitations
            constant_values: list[float] = [c.value for c in self.observable.constants]

            # Check study_interpretation and key_study_limitations for documentation
            combined_text = self.study_interpretation + " " + " ".join(self.key_study_limitations)

            undocumented = []
            for lit in literals:
                # Check if value appears in constants (with tolerance)
                in_constants = any(abs(lit - v) < 1e-6 for v in constant_values)
                # Check if value appears in study_interpretation/key_study_limitations text
                in_text = str(lit) in combined_text or f"{lit:.0e}" in combined_text

                if not (in_constants or in_text):
                    undocumented.append(lit)

            if undocumented:
                warnings.warn(
                    f"observable.code contains numeric literals {undocumented} that may be conversion factors. "
                    f"Document these in observable.constants or explain in study_interpretation. "
                    f"Examples: cell sizes (µm), cellularity fractions, density values, geometric conversion factors.",
                    UserWarning,
                )

        return self

    @model_validator(mode="after")
    def validate_inputs_used(self) -> "CalibrationTarget":
        """Validator: Warn if inputs/assumptions are defined but not used in distribution_code."""
        # Extract all names accessed from 'inputs' dict
        used_input_names = set()

        class InputAccessVisitor(ast.NodeVisitor):
            def visit_Subscript(self, node):
                # Look for inputs['name'] or inputs["name"]
                if isinstance(node.value, ast.Name) and node.value.id == "inputs":
                    if isinstance(node.slice, ast.Constant):
                        used_input_names.add(node.slice.value)
                self.generic_visit(node)

        # Parse distribution_code to find variable references
        try:
            tree = ast.parse(self.empirical_data.distribution_code)
            visitor = InputAccessVisitor()
            visitor.visit(tree)
        except SyntaxError:
            # Already caught by validate_derivation_code
            pass

        # Check which defined inputs/assumptions are not used in distribution_code
        # Both EstimateInputs and ModelingAssumptions are merged into the inputs dict
        defined_inputs = {inp.name for inp in self.empirical_data.inputs}
        defined_assumptions = {a.name for a in self.empirical_data.assumptions}
        all_defined = defined_inputs | defined_assumptions
        unused = all_defined - used_input_names

        if unused:
            # This is a warning, not an error - could be intentional
            import warnings

            warnings.warn(
                f"The following inputs/assumptions are defined but not used in distribution_code: {sorted(unused)}. "
                f"If these are not needed, consider removing them.",
                UserWarning,
            )

        return self

    @model_validator(mode="after")
    def validate_no_hardcoded_constants_in_observable_code(self) -> "CalibrationTarget":
        """
        Validator (ERROR): Flag hardcoded numbers with units in observable.code.

        Uses AST-based detection to find numeric constants multiplied by ureg units.

        All numeric constants with units must be declared in observable.constants
        and accessed via the constants dict. This prevents arbitrary magic numbers
        and forces explicit documentation of biological assumptions.

        Allowed inline numbers:
        - Small integers (0-5)
        - Common fractions (0.5, 0.25, 0.75)
        - Statistical percentiles (2.5, 25, 50, 75, 97.5)
        - Common conversion factors (100, 1000)
        """
        # Skip for IsolatedSystemTarget (uses submodel.observable instead)
        if type(self).__name__ == "IsolatedSystemTarget":
            return self

        from qsp_llm_workflows.core.calibration.code_validator import find_hardcoded_constants

        violations = find_hardcoded_constants(self.observable.code)

        if violations:
            violation_strs = [f"  • {v[0]} in '{v[3]}' (line {v[1]})" for v in violations[:5]]
            raise HardcodedConstantError(
                "Hardcoded numeric constants with units found in observable.code:\n"
                + "\n".join(violation_strs)
                + (f"\n  ... and {len(violations) - 5} more" if len(violations) > 5 else "")
                + "\n\nAll numeric constants with units must be declared in observable.constants "
                + "and accessed via the constants dict.\n"
                + "Example fix:\n"
                + "  1. Add to observable.constants:\n"
                + "     - name: area_per_cancer_cell\n"
                + "       value: 2.27e-4\n"
                + "       units: mm**2/cell\n"
                + "       biological_basis: 'From reference DB pdac_cancer_cell_diameter (17 μm) → area = π×(8.5 μm)²'\n"
                + "       source_type: derived_from_reference_db\n"
                + "       reference_db_names: [pdac_cancer_cell_diameter]\n"
                + "  2. Use in code: area_per_cell = constants['area_per_cancer_cell']"
            )

        return self

    @model_validator(mode="after")
    def validate_no_extreme_dimensionless_constants(self) -> "CalibrationTarget":
        """
        Validator (ERROR): Flag dimensionless constants with extreme magnitude.

        Dimensionless scaling factors > 10 or < 0.1 almost always indicate
        extraction errors rather than legitimate conversion factors. Legitimate
        conversions (cell area, volume, molecular weight) have physical units.

        This catches fudge factors like 'cd8_density_scale = 0.00283' or
        'cd8_fold_scaling_factor = 100' that mask model-data mismatches.
        """
        # Skip for IsolatedSystemTarget (uses submodel.observable instead)
        if type(self).__name__ == "IsolatedSystemTarget":
            return self

        from qsp_llm_workflows.core.unit_registry import ureg

        for const in self.observable.constants:
            try:
                quantity = const.value * ureg(const.units)
                is_dimensionless = quantity.dimensionless
            except Exception:
                is_dimensionless = const.units.strip().lower() in ("dimensionless", "")

            if (
                is_dimensionless
                and const.value != 0
                and (abs(const.value) > 10 or abs(const.value) < 0.1)
            ):
                raise ScaleMismatchError(
                    f"Observable constant '{const.name}' has extreme dimensionless "
                    f"value {const.value}.\n"
                    f"Dimensionless scaling factors > 10 or < 0.1 almost always "
                    f"indicate an extraction error (wrong statistic type, wrong "
                    f"units, cross-arm confusion, or wrong denominator in a ratio).\n\n"
                    f"If this is a legitimate conversion factor, it should have "
                    f"physical units (e.g., mm**2/cell, not dimensionless).\n"
                    f"Re-examine the data extraction before adding scaling factors."
                )

        return self

    @model_validator(mode="after")
    def warn_extreme_constant_magnitude(self) -> "CalibrationTarget":
        """
        Validator (WARNING): Flag constants with very large or very small values.

        Constants with |log10(value)| > 4 (i.e., value > 10000 or value < 0.0001)
        warrant scrutiny even when they have physical units, as they may indicate
        unit mismatches or conversion errors.
        """
        # Skip for IsolatedSystemTarget (uses submodel.observable instead)
        if type(self).__name__ == "IsolatedSystemTarget":
            return self

        import math
        import warnings

        for const in self.observable.constants:
            if const.value == 0:
                continue
            log_magnitude = abs(math.log10(abs(const.value)))
            if log_magnitude > 4:
                warnings.warn(
                    f"Observable constant '{const.name}' has value {const.value} "
                    f"(magnitude ~10^{log_magnitude:.0f}). Constants with extreme "
                    f"magnitude often indicate unit mismatches or conversion errors. "
                    f"Verify the biological_basis is correct and the value uses "
                    f"appropriate units.",
                    UserWarning,
                )

        return self

    @model_validator(mode="after")
    def validate_species_completeness(self) -> "CalibrationTarget":
        """
        Validator (WARNING): Check for potentially missing related species.

        When measuring "total" quantities (e.g., total CD8 via pan-CD8 antibody),
        warns if related species that should be summed are not included.
        """
        # Skip for IsolatedSystemTarget (uses submodel.observable instead)
        if type(self).__name__ == "IsolatedSystemTarget":
            return self

        import warnings

        # Related species pairs - if one is used for a "total" measurement,
        # the other should likely be included too
        RELATED_SPECIES = {
            "V_T.CD8": ["V_T.CD8_exh"],
            "V_T.CD8_exh": ["V_T.CD8"],
            "V_T.Th": ["V_T.Treg"],
            "V_T.Treg": ["V_T.Th"],
            "V_T.M1": ["V_T.M2"],
            "V_T.M2": ["V_T.M1"],
        }

        # Keywords suggesting a "total" measurement
        TOTAL_KEYWORDS = ["total", "all", "overall", "pan-", "combined"]

        interpretation_lower = self.study_interpretation.lower()
        uses_total = any(kw in interpretation_lower for kw in TOTAL_KEYWORDS)

        if not uses_total:
            return self

        used_species = set(self.observable.species)
        for species in self.observable.species:
            related = RELATED_SPECIES.get(species, [])
            missing = [r for r in related if r not in used_species]
            if missing:
                warnings.warn(
                    f"Species completeness: '{species}' used for 'total' measurement "
                    f"but related species {missing} not included.\n"
                    f"If measuring total CD8+ via pan-CD8 antibody, include both CD8 and CD8_exh.",
                    UserWarning,
                )

        return self

    @model_validator(mode="after")
    def validate_no_control_characters(self) -> "CalibrationTarget":
        """
        Validator: Check for control characters in all string fields.

        Control characters (especially in titles, descriptions, snippets) can cause
        YAML parsing failures and other issues. This validator detects them early.

        Checks for:
        - ASCII control characters (0x00-0x1F) except tab (0x09), LF (0x0A), CR (0x0D)
        - DEL character (0x7F)
        - Unicode control characters (U+0080-U+009F)
        """
        import re

        # Pattern to match control characters (excluding valid whitespace)
        # \x00-\x08: NUL through BACKSPACE
        # \x0B-\x0C: VERTICAL TAB, FORM FEED
        # \x0E-\x1F: SHIFT OUT through UNIT SEPARATOR
        # \x7F: DEL
        # \x80-\x9F: Unicode control characters
        control_char_pattern = re.compile(r"[\x00-\x08\x0B-\x0C\x0E-\x1F\x7F\x80-\x9F]")

        def check_string(value: str, field_path: str) -> None:
            """Check a string for control characters."""
            match = control_char_pattern.search(value)
            if match:
                char_code = ord(match.group(0))
                char_hex = f"0x{char_code:02X}"
                # Get position in string
                pos = match.start()
                # Get context around the control character
                context_start = max(0, pos - 20)
                context_end = min(len(value), pos + 20)
                context = value[context_start:context_end]
                # Replace control char with placeholder for display
                context_display = context.replace(match.group(0), f"[{char_hex}]")

                raise ControlCharacterError(
                    f"Control character {char_hex} found in field '{field_path}' at position {pos}.\n"
                    f"Context: ...{context_display}...\n"
                    f"Control characters cause YAML parsing failures and must be removed.\n"
                    f"Common causes: copying from PDFs, word processors, or web pages with special formatting.\n"
                    f"Fix: Re-type the text or use a plain text editor to remove invisible characters."
                )

        def walk_and_check(obj, path: str = "") -> None:
            """Recursively walk through the object and check all strings."""
            if isinstance(obj, str):
                check_string(obj, path)
            elif isinstance(obj, dict):
                for key, value in obj.items():
                    walk_and_check(value, f"{path}.{key}" if path else key)
            elif isinstance(obj, list):
                for i, item in enumerate(obj):
                    walk_and_check(item, f"{path}[{i}]")
            elif hasattr(obj, "model_dump"):
                # Pydantic model - convert to dict and recurse
                walk_and_check(obj.model_dump(), path)

        # Check all fields in the model
        walk_and_check(self.model_dump(), "CalibrationTarget")

        return self
